"""Nadeshiko segment uploader.

Uploads media segments generated by media-sub-splitter to:
- Nadeshiko API (metadata)
- Cloudflare R2 (media files, optional - use --upload-r2 flag)

By default, only the backend is updated without uploading files to R2.
"""

import datetime as dt
import json
import os
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

import boto3
from botocore.config import Config as BotoConfig
from botocore.exceptions import ClientError
from dotenv import load_dotenv
from rich.console import Console
from rich.progress import Progress, TaskID

load_dotenv(override=True)

console = Console()

# Nadeshiko SDK imports — must come after load_dotenv()
from nadeshiko_internal import Nadeshiko, NadeshikoError  # noqa: E402
from nadeshiko_internal.models import (  # noqa: E402
    ContentRating,
    EpisodeCreateRequest,
    ExternalId,
    MediaCreateRequest,
    MediaListResponse,
    MediaUpdateRequest,
    SegmentBatchCreateRequest,
    SegmentCreateRequest,
    SegmentCreateRequestTextEn,
    SegmentCreateRequestTextEs,
    SegmentCreateRequestTextJa,
)
from nadeshiko_internal.types import UNSET  # noqa: E402


def _validate_sdk_contract() -> None:
    """Fail fast when an older SDK shape is installed."""
    contract_checks = {
        "MediaListResponse": (MediaListResponse, {"media", "pagination"}),
        "SegmentCreateRequest": (
            SegmentCreateRequest,
            {"start_time_ms", "end_time_ms", "content_rating"},
        ),
    }
    missing: dict[str, list[str]] = {}
    for name, (model, required_fields) in contract_checks.items():
        present = set(getattr(model, "__annotations__", {}).keys())
        absent = sorted(required_fields - present)
        if absent:
            missing[name] = absent

    if missing:
        details = ", ".join(f"{name}: {fields}" for name, fields in missing.items())
        raise RuntimeError(
            "Unsupported nadeshiko-internal-sdk contract; expected 2.1.0+ fields. "
            f"Missing: {details}"
        )


class SegmentResult(Enum):
    """Result status for segment creation."""

    OK = "OK"
    DUPLICATE = "DUPLICATE"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"


# R2 S3-compatible endpoint
R2_ENDPOINT_TEMPLATE = "https://{account_id}.r2.cloudflarestorage.com"

IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".webp")


def _parse_iso_date(date_str: str | None):
    """Parse an ISO date/datetime string to a date, or return UNSET."""
    if not date_str:
        return UNSET
    try:
        normalized = date_str.strip()
        if normalized.endswith("Z"):
            normalized = f"{normalized[:-1]}+00:00"
        parsed = dt.datetime.fromisoformat(normalized)
        return parsed.date()
    except (ValueError, TypeError):
        return UNSET


def _parse_iso_datetime(date_str: str | None):
    """Parse an ISO date/datetime string to a tz-aware datetime, or return UNSET.

    A bare date (YYYY-MM-DD) is treated as midnight UTC.
    """
    if not date_str:
        return UNSET
    try:
        normalized = date_str.strip()
        if normalized.endswith("Z"):
            normalized = f"{normalized[:-1]}+00:00"
        parsed = dt.datetime.fromisoformat(normalized)
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=dt.UTC)
        return parsed
    except (ValueError, TypeError):
        return UNSET


def _find_image_file(folder: Path, prefix: str) -> Path | None:
    """Find an image file like cover.jpg, cover.png, etc. in a folder."""
    for ext in IMAGE_EXTENSIONS:
        path = folder / f"{prefix}{ext}"
        if path.exists():
            return path
    return None


def _fresh_stats() -> dict:
    """A zeroed per-episode upload stats dict."""
    return {
        "total": 0,
        "uploaded": 0,
        "duplicated": 0,
        "skipped_no_hash": 0,
        "skipped_no_translations": 0,
        "skipped_too_long": 0,
        "skipped_constraint": 0,
        "failed": 0,
        "errors_by_status": {},
    }


@dataclass
class Config:
    """Configuration from environment variables."""

    nadeshiko_api_key: str
    nadeshiko_base_url: str
    r2_account_id: str
    r2_access_key_id: str
    r2_secret_access_key: str
    r2_bucket: str
    r2_public_url: str
    target: str = "local"
    is_prod: bool = False

    @classmethod
    def from_env(cls, env: str = "local") -> "Config":
        if env not in ("local", "dev", "prod"):
            raise ValueError(f"Invalid environment: {env}")

        def _first_set(*names: str, default: str = "") -> str:
            for name in names:
                value = os.getenv(name)
                if value:
                    return value
            return default

        # R2 config is shared across all environments
        r2_kwargs = {
            "r2_account_id": os.getenv("R2_ACCOUNT_ID", ""),
            "r2_access_key_id": os.getenv("R2_ACCESS_KEY_ID", ""),
            "r2_secret_access_key": os.getenv("R2_SECRET_ACCESS_KEY", ""),
            "r2_bucket": os.getenv("R2_BUCKET", "nadeshiko-segments"),
            "r2_public_url": os.getenv("R2_PUBLIC_URL", ""),
        }

        env_config = {
            "local": {
                "nadeshiko_api_key": _first_set("NADESHIKO_LOCAL_API_KEY", "NADESHIKO_API_KEY"),
                "nadeshiko_base_url": _first_set(
                    "NADESHIKO_LOCAL_BASE_URL",
                    "NADESHIKO_BASE_URL",
                    default="http://localhost:5000",
                ),
                "is_prod": False,
            },
            "dev": {
                "nadeshiko_api_key": _first_set("NADESHIKO_DEV_API_KEY", "NADESHIKO_API_KEY"),
                "nadeshiko_base_url": _first_set(
                    "NADESHIKO_DEV_BASE_URL",
                    default="https://api-dev.nadeshiko.co",
                ),
                "is_prod": False,
            },
            "prod": {
                "nadeshiko_api_key": os.getenv("NADESHIKO_PROD_API_KEY", ""),
                "nadeshiko_base_url": os.getenv(
                    "NADESHIKO_PROD_BASE_URL", "https://api.nadeshiko.co"
                ),
                "is_prod": True,
            },
        }

        return cls(**env_config[env], **r2_kwargs, target=env)

    def validate(self, storage_target: str = "local", upload_r2: bool = False) -> bool:
        """Check that required config is present.

        Args:
            storage_target: Where media files should be served from ("local" or "r2").
            upload_r2: Whether files will be uploaded to R2. If False, R2 credentials are optional.
        """
        missing = []
        if not self.nadeshiko_api_key:
            if self.target == "local":
                missing.append("NADESHIKO_LOCAL_API_KEY (or NADESHIKO_API_KEY)")
            elif self.target == "dev":
                missing.append("NADESHIKO_DEV_API_KEY (or NADESHIKO_API_KEY)")
            else:
                missing.append("NADESHIKO_PROD_API_KEY")

        # R2 credentials are required only when files are uploaded to R2.
        needs_r2 = upload_r2

        if needs_r2:
            if not self.r2_public_url:
                missing.append("R2_PUBLIC_URL")
            if not self.r2_account_id:
                missing.append("R2_ACCOUNT_ID")
            if not self.r2_access_key_id:
                missing.append("R2_ACCESS_KEY_ID")
            if not self.r2_secret_access_key:
                missing.append("R2_SECRET_ACCESS_KEY")
            if not self.r2_bucket:
                missing.append("R2_BUCKET")

        if missing:
            console.print(f"[red]Missing required env vars: {', '.join(missing)}[/red]")
            return False
        return True

    def display_target(self) -> None:
        """Display the upload target with appropriate styling."""
        if self.is_prod:
            console.print(
                "\n[bold red on white] TARGET: PRODUCTION [/bold red on white]\n"
                "[bold red] This will upload to PRODUCTION! [/bold red]"
            )
        elif self.target == "dev":
            console.print(
                "\n[bold cyan] TARGET: DEV [/bold cyan]\n"
                f"[dim] API: {self.nadeshiko_base_url}[/dim]"
            )
        else:
            console.print(
                "\n[bold green] TARGET: LOCAL [/bold green]\n"
                f"[dim] API: {self.nadeshiko_base_url}[/dim]"
            )


@dataclass
class SegmentData:
    """Segment data from _data.json."""

    segment_hash: str
    segment_index: int
    start_ms: int
    end_ms: int
    duration_ms: int
    content_ja: str
    content_es: str | None
    content_en: str | None
    is_mt_es: bool
    is_mt_en: bool
    actor_ja: str | None
    actor_es: str | None
    actor_en: str | None
    files: dict[str, str]  # audio, screenshot, video filenames
    subtitles: dict  # ja, es, en subtitle details
    content_rating: str
    content_analysis: dict
    pos_analysis: dict


@dataclass
class EpisodeData:
    """Episode data from _data.json."""

    number: int
    duration_ms: int
    total_segments: int
    segments: list[SegmentData]
    ignored_segments: list[dict]
    external_video_id: str | None = None
    title: str | None = None
    published_at: str | None = None


@dataclass
class MediaInfo:
    """Media info from _info.json."""

    anilist_id: int
    japanese_name: str | None
    english_name: str | None
    romaji_name: str
    airing_format: str
    airing_status: str
    genres: list[str]
    version: str
    hash_salt: str
    cover_url: str | None
    banner_url: str | None
    start_date: str | None  # ISO format date string (YYYY-MM-DD)
    end_date: str | None  # ISO format date string (YYYY-MM-DD)
    characters: list[dict] | None = None
    studio: str | None = None
    season_name: str | None = None
    season_year: int | None = None
    media_source: str = "anilist"  # "anilist", "tmdb" or "youtube"
    category: str = "ANIME"  # "ANIME", "JDRAMA" or "YOUTUBE"
    tmdb_season: int | None = None  # TMDB season number (1-based) for multi-season shows

    @property
    def source(self) -> "MediaSource":
        return get_media_source(self.media_source)


class MediaSource:
    """Per-source behaviour for the uploader: identity, storage layout, episode
    numbering, and the source-specific media-create fields.

    One concrete subclass per ``media_source`` keeps the differences between
    AniList anime, TMDB drama and YouTube channels in a single place instead of
    scattered ``if is_youtube`` checks across the uploader.
    """

    key: str  # the ExternalId field this source populates
    requires_season = True  # whether create must supply a season (anime/drama)
    episode_is_surrogate = False  # whether episode numbers are surrogates reconciled by the backend

    def external_ids(self, info: "MediaInfo") -> ExternalId:
        raise NotImplementedError

    def storage_base_path(self, info: "MediaInfo") -> str:
        raise NotImplementedError

    def episode_number(self, folder: Path, surrogate: int) -> int | None:
        """Episode number for a folder, or None if it isn't an episode folder.

        Anime/drama folders are named by their episode number; the default
        parses it. YouTube overrides this to hand out sequential surrogates.
        """
        try:
            return int(folder.name)
        except ValueError:
            return None

    def create_descriptors(self, info: "MediaInfo") -> dict:
        """Source-specific MediaCreateRequest fields (airing/genres/category/season).

        Raises ValueError with a user-facing message when a required field
        cannot be determined.
        """
        raise NotImplementedError

    def summary_identity(self, data: dict) -> tuple[object, str | None]:
        """(media_id, title) read straight from _info.json for the dry-run summary."""
        return data.get("anilist_id", data.get("id")), data.get("romaji_name")


class _CatalogSource(MediaSource):
    """Shared behaviour for media from external catalogs (AniList, TMDB) — anime,
    drama or film. They carry release dates and the season metadata the API
    requires, and their episode numbers are the episode's identity. Contrast
    YouTube, whose channel videos use surrogate numbers."""

    def create_descriptors(self, info: "MediaInfo") -> dict:
        season_name = info.season_name
        season_year = info.season_year
        # Derive season from start_date when the metadata omits it.
        if not season_name and info.start_date:
            month = int(info.start_date.split("-")[1])
            season_name = (
                "WINTER"
                if month <= 3
                else "SPRING"
                if month <= 6
                else "SUMMER"
                if month <= 9
                else "FALL"
            )
        if season_year is None and info.start_date:
            season_year = int(info.start_date.split("-")[0])

        if not season_name:
            raise ValueError("season_name could not be determined (no season or start_date)")
        if season_year is None:
            raise ValueError("season_year could not be determined (no season or start_date)")

        return {
            "airing_format": info.airing_format,
            "airing_status": info.airing_status,
            "genres": info.genres,
            "category": "JDRAMA" if info.category == "JDRAMA" else "ANIME",
            "season_name": season_name,
            "season_year": season_year,
        }


class AnilistSource(_CatalogSource):
    key = "anilist"

    def external_ids(self, info: "MediaInfo") -> ExternalId:
        return ExternalId(
            anilist=str(info.anilist_id), imdb=None, tvdb=None, tmdb=None, youtube=None
        )

    def storage_base_path(self, info: "MediaInfo") -> str:
        return f"media/{info.anilist_id}"


class TmdbSource(_CatalogSource):
    key = "tmdb"

    def external_ids(self, info: "MediaInfo") -> ExternalId:
        # Each TMDB season is a distinct media: id "46198_1", "46198_2", ...
        id_str = str(info.anilist_id)
        if info.tmdb_season is not None:
            id_str = f"{id_str}_{info.tmdb_season}"
        return ExternalId(anilist=None, imdb=None, tvdb=None, tmdb=id_str, youtube=None)

    def storage_base_path(self, info: "MediaInfo") -> str:
        base = f"media/mv/{info.anilist_id}"
        if info.tmdb_season is not None:
            base = f"{base}_{info.tmdb_season}"
        return base


class YoutubeSource(MediaSource):
    key = "youtube"
    requires_season = False
    episode_is_surrogate = True

    def external_ids(self, info: "MediaInfo") -> ExternalId:
        return ExternalId(
            anilist=None, imdb=None, tvdb=None, tmdb=None, youtube=str(info.anilist_id)
        )

    def storage_base_path(self, info: "MediaInfo") -> str:
        return f"media/yt/{info.anilist_id}"

    def episode_number(self, folder: Path, surrogate: int) -> int | None:
        # Folders are video IDs; the backend reconciles the surrogate via external_video_id.
        return surrogate

    def create_descriptors(self, info: "MediaInfo") -> dict:
        # The API requires these anime/drama fields, so YouTube supplies dedicated
        # enum members: airing_format/category YOUTUBE, season_name NONE. season_year
        # has no channel-level source, so it carries the ingestion year.
        return {
            "airing_format": "YOUTUBE",
            "airing_status": "FINISHED",
            "genres": ["STREAMING"],
            "category": "YOUTUBE",
            "season_name": "NONE",
            "season_year": dt.date.today().year,
        }

    def summary_identity(self, data: dict) -> tuple[object, str | None]:
        return data.get("channel_id"), data.get("name")


MEDIA_SOURCES: dict[str, MediaSource] = {
    "anilist": AnilistSource(),
    "tmdb": TmdbSource(),
    "youtube": YoutubeSource(),
}


def get_media_source(media_source: str) -> MediaSource:
    """Return the strategy for a media_source string (defaults to AniList anime)."""
    return MEDIA_SOURCES.get(media_source, MEDIA_SOURCES["anilist"])


class R2Uploader:
    """Handles file uploads to Cloudflare R2."""

    def __init__(self, config: Config):
        self.config = config
        self.endpoint = R2_ENDPOINT_TEMPLATE.format(account_id=config.r2_account_id)
        self.bucket = config.r2_bucket
        self.public_url = config.r2_public_url

        self.s3_client = boto3.client(
            "s3",
            endpoint_url=self.endpoint,
            region_name="auto",
            aws_access_key_id=config.r2_access_key_id,
            aws_secret_access_key=config.r2_secret_access_key,
            config=BotoConfig(max_pool_connections=50),
        )

    def get_r2_key(self, storage_base_path: str, folder: str | int, filename: str) -> str:
        """Generate R2 object key for a file.

        `folder` is the per-item storage folder: the episode number for anime/
        drama, or the YouTube video ID for YouTube channels (matching the
        backend's segment URL builder).
        """
        return f"{storage_base_path}/{folder}/{filename}"

    def upload_file(
        self,
        filepath: Path,
        storage_base_path: str,
        folder: str | int,
        progress: Progress | None = None,
        task_id: TaskID | None = None,
    ) -> str | None:
        """Upload a file to R2 and return its public URL."""
        key = self.get_r2_key(storage_base_path, folder, filepath.name)

        try:
            callback = None
            if progress and task_id:

                def callback(bytes_transferred):
                    progress.update(task_id, advance=bytes_transferred)

            self.s3_client.upload_file(
                str(filepath),
                self.bucket,
                key,
                Callback=callback,
            )
            # Return public URL
            return f"{self.public_url}/{key}"
        except ClientError as e:
            console.print(f"[red]Error uploading {filepath.name}: {e}[/red]")
            return None

    def file_exists(self, storage_base_path: str, folder: str | int, filename: str) -> bool:
        """Check if a file already exists in R2."""
        key = self.get_r2_key(storage_base_path, folder, filename)
        try:
            self.s3_client.head_object(Bucket=self.bucket, Key=key)
            return True
        except ClientError:
            return False

    def list_existing_files(self, storage_base_path: str, folder: str | int) -> set[str]:
        """List all existing filenames in an item's R2 prefix in a single call."""
        prefix = f"{storage_base_path}/{folder}/"
        existing: set[str] = set()
        try:
            paginator = self.s3_client.get_paginator("list_objects_v2")
            for page in paginator.paginate(Bucket=self.bucket, Prefix=prefix):
                for obj in page.get("Contents", []):
                    existing.add(obj["Key"].split("/")[-1])
        except ClientError as e:
            console.print(f"[yellow]Warning: could not list R2 prefix {prefix}: {e}[/yellow]")
        return existing

    def get_media_r2_key(self, storage_base_path: str, filename: str) -> str:
        """Generate R2 object key for a media-level file (cover/banner)."""
        return f"{storage_base_path}/{filename}"

    def upload_media_file(self, filepath: Path, storage_base_path: str) -> str | None:
        """Upload a media-level file (cover/banner) to R2 and return its public URL."""
        key = self.get_media_r2_key(storage_base_path, filepath.name)

        try:
            self.s3_client.upload_file(str(filepath), self.bucket, key)
            return f"{self.public_url}/{key}"
        except ClientError as e:
            console.print(f"[red]Error uploading {filepath.name}: {e}[/red]")
            return None

    def media_file_exists(self, storage_base_path: str, filename: str) -> bool:
        """Check if a media-level file already exists in R2."""
        key = self.get_media_r2_key(storage_base_path, filename)
        try:
            self.s3_client.head_object(Bucket=self.bucket, Key=key)
            return True
        except ClientError:
            return False

    def get_media_file_url(self, storage_base_path: str, filename: str) -> str:
        """Get the public URL for a media-level file."""
        key = self.get_media_r2_key(storage_base_path, filename)
        return f"{self.public_url}/{key}"


_RATE_LIMIT_WAIT_SECONDS = 60  # Fixed 1 minute wait for rate limits


class NadeshikoUploader:
    """Handles uploading to Nadeshiko API and R2."""

    # Maximum content length for segments (characters)
    MAX_CONTENT_LENGTH = 500

    def __init__(
        self,
        config: Config,
        dry_run: bool = False,
        storage_target: str = "local",
        upload_r2: bool = False,
        update_info_only: bool = False,
    ):
        _validate_sdk_contract()
        self.config = config
        self.dry_run = dry_run
        self.storage_target = storage_target
        self.upload_r2 = upload_r2
        self.update_info_only = update_info_only
        # Only initialize R2Uploader when we'll actually use it
        self.r2 = R2Uploader(config) if upload_r2 else None

        self.api_client = Nadeshiko(
            api_key=config.nadeshiko_api_key,
            base_url=config.nadeshiko_base_url,
            headers={"User-Agent": "NadeshikoDevTools/1.0"},
        )
        self._console_lock = threading.Lock()
        self.stats = _fresh_stats()

        if dry_run:
            console.print(
                "[cyan]Running in DRY-RUN mode. Use --apply to perform actual uploads.[/cyan]"
            )

    def _should_skip_segment(self, segment: SegmentData) -> tuple[bool, str]:
        """Check if a segment should be skipped and return (skip, reason)."""
        # Check if segment has a valid hash
        if not segment.segment_hash:
            return True, "no segment hash"

        # Check if segment has all three translations
        if not segment.content_es:
            return True, "no Spanish translation"
        if not segment.content_en:
            return True, "no English translation"

        # Check if any content field is too long
        for field, value in [
            ("ja", segment.content_ja),
            ("en", segment.content_en),
            ("es", segment.content_es),
        ]:
            if value and len(value) > self.MAX_CONTENT_LENGTH:
                return True, f"content too long ({field}: {len(value)} > {self.MAX_CONTENT_LENGTH})"

        return False, ""

    def _segment_content_rating(self, segment: SegmentData) -> ContentRating:
        """Return the ContentRating literal for a segment."""
        rating = (segment.content_rating or "").strip().upper()
        valid = {"EXPLICIT", "QUESTIONABLE", "SAFE", "SUGGESTIVE"}
        return rating if rating in valid else "SAFE"

    def _print(self, *args, **kwargs) -> None:
        """Thread-safe console print."""
        with self._console_lock:
            console.print(*args, **kwargs)

    def _upload_media_images(self, media_folder: Path, storage_base_path: str) -> None:
        """Upload cover and banner images to R2 if they exist locally."""
        if not self.upload_r2 or not self.r2:
            return

        for prefix in ("cover", "banner"):
            image_path = _find_image_file(media_folder, prefix)
            if not image_path:
                continue
            if not self.r2.media_file_exists(storage_base_path, image_path.name):
                self.r2.upload_media_file(image_path, storage_base_path)
                console.print(f"[green]Uploaded {prefix}: {image_path.name}[/green]")
            else:
                console.print(
                    f"[dim]{prefix.capitalize()} already uploaded: {image_path.name}[/dim]"
                )

    def _update_media_info(
        self,
        existing_media,
        media_info: MediaInfo,
        media_folder: Path,
        storage_base_path: str = "",
    ) -> str | None:
        """Update existing media with storage backend and other info."""
        if self.dry_run:
            console.print(f"[cyan][DRY RUN] Would update media: {existing_media.public_id}[/cyan]")
            return existing_media.public_id

        console.print(f"[cyan]Updating media info: {existing_media.public_id}[/cyan]")

        storage = "R2" if self.storage_target == "r2" else "LOCAL"

        self._upload_media_images(media_folder, storage_base_path)

        start_date = _parse_iso_date(media_info.start_date)
        end_date = _parse_iso_date(media_info.end_date)

        # Build update request with only fields that are set
        request = MediaUpdateRequest()
        request.storage = storage
        request.external_ids = media_info.source.external_ids(media_info)
        if start_date is not UNSET:
            request.start_date = start_date
        if end_date is not UNSET:
            request.end_date = end_date
        if media_info.studio:
            request.studio = media_info.studio
        if media_info.season_name:
            request.season_name = media_info.season_name
        if media_info.season_year is not None:
            request.season_year = media_info.season_year
        if media_info.hash_salt:
            request.hash_salt = media_info.hash_salt
        if media_info.version:
            request.version = media_info.version
        if storage_base_path:
            request.storage_base_path = storage_base_path

        try:
            self.api_client.update_media(media_public_id=existing_media.public_id, body=request)
            console.print(f"[green]Updated media: {existing_media.public_id}[/green]")
        except NadeshikoError as e:
            console.print(f"\n[red]Failed to update media: {e.detail}[/red]")
        return existing_media.public_id  # Return ID anyway if update failed

    def _load_media_info(self, media_folder: Path) -> MediaInfo | None:
        """Load _info.json from a media folder."""
        info_path = media_folder / "_info.json"
        if not info_path.exists():
            console.print(f"[yellow]No _info.json found in {media_folder}[/yellow]")
            return None

        with open(info_path) as f:
            data = json.load(f)

        if data.get("media_source") == "youtube":
            return self._load_youtube_media_info(data)

        return MediaInfo(
            anilist_id=data.get("anilist_id", data.get("id")),
            japanese_name=data.get("japanese_name"),
            english_name=data.get("english_name"),
            romaji_name=data.get("romaji_name"),
            airing_format=data.get("airing_format", "TV"),
            airing_status=data.get("airing_status", "FINISHED"),
            genres=data.get("genres", []),
            version=data.get("version", "1.0"),
            hash_salt=data.get("hash_salt", ""),
            cover_url=data.get("cover_url"),
            banner_url=data.get("banner_url"),
            start_date=data.get("start_date"),
            end_date=data.get("end_date"),
            characters=data.get("characters"),
            studio=data.get("studio"),
            season_name=data.get("season", {}).get("name"),
            season_year=data.get("season", {}).get("year"),
            media_source=data.get("media_source", "anilist"),
            category=data.get("category", "ANIME"),
            tmdb_season=data.get("tmdb_season"),
        )

    @staticmethod
    def _load_youtube_media_info(data: dict) -> MediaInfo:
        """Map a YouTube channel _info.json to MediaInfo.

        The channel name is the only title. The anime/drama descriptive fields
        the API requires (airing_format, season, ...) are supplied by
        ``YoutubeSource.create_descriptors`` at create time, so they're left
        blank here. Cover/banner are local files uploaded from the channel folder.
        """
        name = data.get("name") or data.get("channel_id", "")
        return MediaInfo(
            anilist_id=data["channel_id"],
            japanese_name=name,
            english_name=name,
            romaji_name=name,
            airing_format="",
            airing_status="",
            genres=[],
            version=data.get("version", "6"),
            hash_salt=data.get("hash_salt", ""),
            cover_url=None,
            banner_url=None,
            start_date=None,
            end_date=None,
            media_source="youtube",
        )

    @staticmethod
    def _load_nsfw_lookup(media_folder: Path) -> dict[str, dict]:
        """Load _nsfw_results/results.json and return a flat {hashed_id: result} lookup."""
        results_path = media_folder / "_nsfw_results" / "results.json"
        if not results_path.exists():
            return {}
        with open(results_path) as f:
            data = json.load(f)
        lookup: dict[str, dict] = {}
        for ep_data in data.values():
            for hashed_id, result in ep_data.items():
                lookup[hashed_id] = result
        return lookup

    def _load_episode_data(
        self, episode_folder: Path, nsfw_lookup: dict[str, dict] | None = None
    ) -> EpisodeData | None:
        """Load _data.json from an episode folder."""
        data_path = episode_folder / "_data.json"
        if not data_path.exists():
            console.print(f"[yellow]No _data.json found in {episode_folder}[/yellow]")
            return None

        with open(data_path) as f:
            data = json.load(f)

        metadata = data.get("metadata", {})
        segments = []
        for s in data.get("segments", []):
            seg_hash = s.get("segment_hash", "")
            nsfw = (nsfw_lookup or {}).get(seg_hash, {})

            content_rating = nsfw.get("content_rating") or s.get("content_rating")
            if not content_rating:
                console.print(
                    f"[red]Missing content_rating for segment {seg_hash} in {episode_folder}[/red]"
                )
                return None

            if nsfw:
                content_analysis = {"scores": nsfw["scores"], "tags": nsfw["tags"]}
            else:
                content_analysis = s.get("content_analysis")
            if not content_analysis:
                console.print(
                    f"[red]Missing content_analysis for segment {seg_hash}"
                    f" in {episode_folder}[/red]"
                )
                return None

            pos_analysis = s.get("pos_analysis")
            if not pos_analysis:
                console.print(
                    f"[red]Missing pos_analysis for segment {seg_hash} in {episode_folder}[/red]"
                )
                return None

            segments.append(
                SegmentData(
                    segment_hash=seg_hash,
                    segment_index=s.get("segment_index", 0),
                    start_ms=s.get("start_ms", 0),
                    end_ms=s.get("end_ms", 0),
                    duration_ms=s.get("duration_ms", 0),
                    content_ja=s.get("content_ja", ""),
                    content_es=s.get("content_es"),
                    content_en=s.get("content_en"),
                    is_mt_es=s.get("is_mt_es", False),
                    is_mt_en=s.get("is_mt_en", False),
                    actor_ja=s.get("actor_ja"),
                    actor_es=s.get("actor_es"),
                    actor_en=s.get("actor_en"),
                    files=s.get("files", {}),
                    subtitles=s.get("subtitles", {}),
                    content_rating=content_rating,
                    content_analysis=content_analysis,
                    pos_analysis=pos_analysis,
                )
            )

        return EpisodeData(
            number=metadata.get("number", 0),
            duration_ms=metadata.get("duration_ms", 0),
            total_segments=metadata.get("total_segments", 0),
            segments=segments,
            ignored_segments=data.get("ignored_segments", []),
            external_video_id=metadata.get("video_id"),
            title=metadata.get("title"),
            published_at=metadata.get("published_at"),
        )

    def _get_or_create_media(
        self,
        media_info: MediaInfo,
        media_folder: Path,
    ) -> tuple[str, str] | None:
        """Get existing media or create new one.

        Returns (media_public_id, storage_base_path) or None on failure.
        """
        source = media_info.source
        storage_base_path = source.storage_base_path(media_info)

        if self.dry_run or not self.api_client:
            console.print(
                f"[cyan][DRY RUN] Would get/create media: {media_info.romaji_name}[/cyan]"
            )
            return str(media_info.anilist_id), storage_base_path

        existing_media = None
        try:
            for media in self.api_client.iter_list_media():
                ext_ids = getattr(media, "external_ids", UNSET)
                if ext_ids is UNSET or ext_ids is None:
                    continue
                ext_id_val = getattr(ext_ids, source.key, None)
                if str(ext_id_val) == str(media_info.anilist_id):
                    console.print(f"[green]Found existing media: {media.public_id}[/green]")
                    existing_media = media
                    break
        except NadeshikoError as e:
            if e.status == 401:
                console.print(
                    "[red]Authentication failed while listing media. "
                    "Check your API key for the selected target (local/dev/prod).[/red]"
                )
            else:
                console.print(f"\n[red]Failed to list media: {e.detail}[/red]")
            return None

        # If media exists, always sync media info (including characters).
        # `--update-info` only controls whether episodes/segments are skipped later.
        if existing_media:
            media_public_id = self._update_media_info(
                existing_media,
                media_info,
                media_folder,
                storage_base_path=storage_base_path,
            )
            return media_public_id or existing_media.public_id, storage_base_path

        # Determine storage backend
        storage = "R2" if self.storage_target == "r2" else "LOCAL"

        if not _find_image_file(media_folder, "cover"):
            console.print(
                "[red]Error: cover image is required but not found. "
                "Add cover.jpg/png/webp to the media folder[/red]"
            )
            return None

        start_date = _parse_iso_date(media_info.start_date)
        if start_date is UNSET:
            start_date = dt.date(1970, 1, 1)
        end_date = _parse_iso_date(media_info.end_date)

        try:
            descriptors = source.create_descriptors(media_info)
        except ValueError as e:
            console.print(f"[red]Error: {e}[/red]")
            return None

        self._upload_media_images(media_folder, storage_base_path)

        request = MediaCreateRequest(
            name_ja=media_info.japanese_name or media_info.romaji_name,
            name_romaji=media_info.romaji_name,
            name_en=media_info.english_name or media_info.romaji_name,
            version=media_info.version,
            studio=media_info.studio if media_info.studio else UNSET,
            hash_salt=media_info.hash_salt,
            storage=storage,
            start_date=start_date,
            end_date=end_date,
            external_ids=source.external_ids(media_info),
            storage_base_path=storage_base_path,
            **descriptors,
        )

        create_result = self._do_create_media(request)
        if not create_result:
            return None

        console.print(f"[green]Created new media: {create_result.public_id}[/green]")
        return create_result.public_id, storage_base_path

    def _do_create_media(self, request):
        """Send create media request."""
        try:
            return self.api_client.create_media(body=request)
        except NadeshikoError as e:
            console.print(f"\n[red]Failed to create media: {e.detail}[/red]")
            return None

    def _get_or_create_episode(
        self, media_public_id: str, episode_data: EpisodeData, source: MediaSource
    ) -> int | None:
        """Get or create the episode; return its canonical episode number (None on failure)."""
        if self.dry_run or not self.api_client:
            console.print(
                f"[cyan][DRY RUN] Would get/create episode: E{episode_data.number}[/cyan]"
            )
            return episode_data.number

        if not source.episode_is_surrogate:
            try:
                self.api_client.get_episode(
                    media_public_id=media_public_id, episode_number=episode_data.number
                )
                console.print(f"[green]Found existing episode: E{episode_data.number}[/green]")
                return episode_data.number
            except NadeshikoError as e:
                if e.status == 401:
                    console.print(
                        "[red]Authentication failed while checking episodes. "
                        "Check your API key for the selected target (local/dev/prod).[/red]"
                    )
                    return None
                if e.status != 404:
                    console.print(
                        f"[red]Failed to check episode E{episode_data.number}: {e.detail}[/red]"
                    )
                    return None

        request = EpisodeCreateRequest(
            episode_number=episode_data.number,
            external_video_id=episode_data.external_video_id or UNSET,
            title_ja=episode_data.title or UNSET,
            aired_at=_parse_iso_datetime(episode_data.published_at),
        )
        try:
            result = self.api_client.create_episode(media_public_id=media_public_id, body=request)
            canonical = getattr(result, "episode_number", episode_data.number)
            label = episode_data.external_video_id or f"E{canonical}"
            console.print(f"[green]Created/linked episode: {label} (E{canonical})[/green]")
            return canonical
        except NadeshikoError as e:
            console.print(f"[red]Failed to create episode {episode_data.number}: {e.detail}[/red]")
            return None

    def _build_segment_request(self, segment: SegmentData) -> SegmentCreateRequest:
        """Build a SegmentCreateRequest from a SegmentData."""
        storage = "R2" if self.storage_target == "r2" else "LOCAL"

        ja = SegmentCreateRequestTextJa(content=segment.content_ja)
        es = (
            SegmentCreateRequestTextEs(
                content=segment.content_es,
                is_machine_translated=segment.is_mt_es,
            )
            if segment.content_es
            else UNSET
        )
        en = (
            SegmentCreateRequestTextEn(
                content=segment.content_en,
                is_machine_translated=segment.is_mt_en,
            )
            if segment.content_en
            else UNSET
        )

        return SegmentCreateRequest(
            position=segment.segment_index,
            start_time_ms=segment.start_ms,
            end_time_ms=segment.end_ms,
            text_ja=ja,
            text_es=es,
            text_en=en,
            content_rating=self._segment_content_rating(segment),
            rating_analysis=segment.content_analysis or UNSET,
            pos_analysis=segment.pos_analysis or UNSET,
            storage=storage,
            hashed_id=segment.segment_hash,
        )

    def _create_segments_batch(
        self,
        media_public_id: str,
        episode_number: int,
        requests: list[SegmentCreateRequest],
        chunk_size: int = 500,
    ) -> tuple[int, int, int]:
        """Create segments in batches via the batch API endpoint.

        Returns:
            (created, skipped, failed) counts.
        """
        if not requests:
            return 0, 0, 0

        total_created = 0
        total_skipped = 0
        total_failed = 0

        for i in range(0, len(requests), chunk_size):
            chunk = requests[i : i + chunk_size]
            try:
                result = self.api_client.create_segments_batch(
                    media_public_id=media_public_id,
                    episode_number=episode_number,
                    body=SegmentBatchCreateRequest(segments=chunk),
                )
                total_created += result.created
                total_skipped += result.skipped
            except NadeshikoError as e:
                if e.status == 429:
                    wait = _RATE_LIMIT_WAIT_SECONDS
                    console.print(f"[yellow]Rate limited. Waiting {wait}s...[/yellow]")
                    time.sleep(wait)
                    try:
                        result = self.api_client.create_segments_batch(
                            media_public_id=media_public_id,
                            episode_number=episode_number,
                            body=SegmentBatchCreateRequest(segments=chunk),
                        )
                        total_created += result.created
                        total_skipped += result.skipped
                        continue
                    except NadeshikoError as e2:
                        e = e2

                key = f"HTTP_{e.status}" if e.status else "api_error_no_status"
                self.stats["errors_by_status"][key] = (
                    self.stats["errors_by_status"].get(key, 0) + 1
                )
                console.print(f"[red]Batch failed: {e.detail}[/red]")
                if e.status == 401:
                    console.print("[red]Authentication error — aborting.[/red]")
                    total_failed += len(requests) - i
                    return total_created, total_skipped, total_failed
                total_failed += len(chunk)

        return total_created, total_skipped, total_failed

    def upload_media(self, media_folder: Path, episode_filter: int | None = None) -> bool:
        """Upload a single media (all episodes and segments).

        Args:
            media_folder: Path to the media folder
            episode_filter: Optional episode number to filter upload
        """
        media_id_str = media_folder.name

        console.print(f"\n[bold cyan]Processing: {media_id_str}[/bold cyan]")

        # Load media info
        media_info = self._load_media_info(media_folder)
        if not media_info:
            return False

        # Get or create media
        result = self._get_or_create_media(media_info, media_folder)
        if not result:
            return False

        media_public_id, storage_base_path = result

        # Skip episodes if update_info_only is True
        if self.update_info_only:
            console.print("[cyan]Info-only mode: Skipping episode/segment processing[/cyan]")
            return True

        nsfw_lookup = self._load_nsfw_lookup(media_folder)
        if nsfw_lookup:
            console.print(f"[dim]Loaded NSFW lookup: {len(nsfw_lookup)} segments[/dim]")
        else:
            console.print(
                "[yellow]No _nsfw_results/results.json found"
                " — content_rating must be in _data.json[/yellow]"
            )

        # Process each episode folder
        episode_folders = sorted(
            [d for d in media_folder.iterdir() if d.is_dir() and not d.name.startswith("_")]
        )

        source = media_info.source

        has_errors = False
        for surrogate, episode_folder in enumerate(episode_folders, start=1):
            episode_number = source.episode_number(episode_folder, surrogate)
            if episode_number is None:
                console.print(
                    f"[yellow]Skipping non-episode folder: {episode_folder.name}[/yellow]"
                )
                continue

            if episode_filter and episode_number != episode_filter:
                continue

            try:
                ep_ok = self.upload_episode(
                    media_public_id,
                    episode_folder,
                    source,
                    episode_number,
                    storage_base_path=storage_base_path,
                    nsfw_lookup=nsfw_lookup,
                )
            except Exception as e:
                console.print(f"[red]Episode {episode_number} failed with error: {e}[/red]")
                ep_ok = False

            if not ep_ok:
                has_errors = True

        return not has_errors

    def _upload_segment_files(
        self,
        storage_base_path: str,
        storage_folder: str | int,
        segment: SegmentData,
        episode_folder: Path,
        existing_files: set[str],
    ) -> tuple[str, list[str], list[str]]:
        """Upload R2 files for a single segment. Returns (segment_hash, uploaded, skipped)."""
        uploaded: list[str] = []
        skipped: list[str] = []

        for _file_type, filename in segment.files.items():
            if not filename:
                continue
            filepath = episode_folder / filename
            if not filepath.exists():
                continue

            if filename in existing_files:
                skipped.append(filename)
            else:
                url = self.r2.upload_file(filepath, storage_base_path, storage_folder)
                if url:
                    uploaded.append(filename)
                else:
                    uploaded.append(f"{filename} (FAILED)")

        return segment.segment_hash, uploaded, skipped

    def upload_episode(
        self,
        media_public_id: str,
        episode_folder: Path,
        source: MediaSource,
        episode_number: int,
        max_r2_workers: int = 30,
        storage_base_path: str = "",
        nsfw_lookup: dict[str, dict] | None = None,
    ) -> bool:
        """Upload a single episode using two-phase processing.

        Phase 1: Upload all files to R2 with high concurrency.
        Phase 2: Create segments via individual API calls.
        """
        self.stats = _fresh_stats()

        console.print(f"\n[cyan]Processing episode: {episode_folder.name}[/cyan]")

        episode_data = self._load_episode_data(episode_folder, nsfw_lookup=nsfw_lookup)
        if not episode_data:
            return False

        episode_data.number = episode_number

        canonical_number = self._get_or_create_episode(media_public_id, episode_data, source)
        if canonical_number is None:
            return False

        total = len(episode_data.segments)
        episode_number = canonical_number
        storage_folder: str | int = episode_data.external_video_id or canonical_number

        # --- Phase 1: R2 file uploads (high concurrency, no rate limiting) ---
        if self.upload_r2 and self.r2 and not self.dry_run:
            console.print(
                f"[cyan]Phase 1: Uploading files to R2 ({max_r2_workers} workers)...[/cyan]"
            )

            # Batch existence check — one list call replaces hundreds of head_object calls
            existing_files = self.r2.list_existing_files(storage_base_path, storage_folder)
            console.print(f"[dim]  Found {len(existing_files)} files already in R2[/dim]")

            # Collect segments that need file uploads
            segments_needing_upload = [
                seg
                for seg in episode_data.segments
                if not self._should_skip_segment(seg)[0]
                and any(
                    (episode_folder / fn).exists() and fn not in existing_files
                    for fn in seg.files.values()
                    if fn
                )
            ]

            if segments_needing_upload:
                total_r2_uploaded = 0
                total_r2_skipped = 0

                with ThreadPoolExecutor(max_workers=max_r2_workers) as upload_pool:
                    futures = {
                        upload_pool.submit(
                            self._upload_segment_files,
                            storage_base_path,
                            storage_folder,
                            segment,
                            episode_folder,
                            existing_files,
                        ): segment
                        for segment in segments_needing_upload
                    }

                    for future in as_completed(futures):
                        try:
                            seg_hash, uploaded, skipped = future.result()
                            total_r2_uploaded += len([f for f in uploaded if "(FAILED)" not in f])
                            total_r2_skipped += len(skipped)
                        except Exception as e:
                            segment = futures[future]
                            self._print(
                                f"[red]  R2 upload error for {segment.segment_hash}: {e}[/red]"
                            )

                console.print(
                    f"[green]  R2 done: {total_r2_uploaded} uploaded, "
                    f"{total_r2_skipped} already existed[/green]"
                )
            else:
                console.print("[dim]  All files already in R2, skipping upload phase[/dim]")
        elif self.upload_r2 and self.dry_run:
            console.print("[cyan]Phase 1: [DRY RUN] Would upload files to R2[/cyan]")

        # --- Phase 2: Segment API calls ---
        console.print(f"[cyan]Phase 2: Creating {total} segments...[/cyan]")

        # Filter and build requests
        api_requests: list[SegmentCreateRequest] = []
        for segment in episode_data.segments:
            self.stats["total"] += 1
            should_skip, skip_reason = self._should_skip_segment(segment)
            if should_skip:
                if skip_reason == "no segment hash":
                    self.stats["skipped_no_hash"] += 1
                elif "translation" in skip_reason:
                    self.stats["skipped_no_translations"] += 1
                elif "content too long" in skip_reason:
                    self.stats["skipped_too_long"] += 1
                continue
            api_requests.append(self._build_segment_request(segment))

        valid_count = len(api_requests)
        skipped_count = total - valid_count
        if skipped_count:
            console.print(f"[dim]  {skipped_count} segments skipped (pre-filter)[/dim]")

        if self.dry_run:
            console.print(
                f"[cyan][DRY RUN] Would create {valid_count} segments"
                f" in batch (from {total} total)[/cyan]"
            )
            for req in api_requests:
                ja_content = getattr(req.text_ja, "content", "?")
                preview = ja_content[:30] + "..." if len(ja_content) > 30 else ja_content
                console.print(f"  [dim]{req.hashed_id} pos={req.position} {preview}[/dim]")
            self.stats["uploaded"] = valid_count
        elif api_requests:
            created, duped, failed = self._create_segments_batch(
                media_public_id,
                episode_number,
                api_requests,
            )
            self.stats["uploaded"] = created
            self.stats["duplicated"] = duped
            self.stats["failed"] = failed

        console.print(
            f"[green]Completed episode {episode_number}:[/green] "
            f"{total} total, "
            f"[green]{self.stats['uploaded']} ok[/green], "
            f"[yellow]{self.stats['duplicated']} duplicated[/yellow], "
            f"[red]{self.stats['failed']} failed[/red]"
        )

        # Print detailed statistics
        s = self.stats
        parts = []
        if s["skipped_no_hash"] > 0:
            parts.append(f"[dim]no hash: {s['skipped_no_hash']}[/dim]")
        if s["skipped_no_translations"] > 0:
            parts.append(f"[dim]no translations: {s['skipped_no_translations']}[/dim]")
        if s["skipped_too_long"] > 0:
            parts.append(f"[dim]too long: {s['skipped_too_long']}[/dim]")
        if s["skipped_constraint"] > 0:
            parts.append(f"[dim]constraint: {s['skipped_constraint']}[/dim]")
        if parts:
            console.print(f"  Skipped: {', '.join(parts)}")

        # Print error breakdown by status code
        if s["errors_by_status"]:
            console.print("  [bold]Error breakdown:[/bold]")
            for error_type, count in sorted(s["errors_by_status"].items()):
                console.print(f"    [red]{error_type}:[/red] {count}")

        return self.stats["failed"] == 0


def scan_output_directory(output_path: Path) -> list[Path]:
    """Scan output directory for media folders."""
    media_folders = []

    for item in output_path.iterdir():
        if item.is_dir() and not item.name.startswith("_") and (item / "_info.json").exists():
            media_folders.append(item)

    return sorted(media_folders, key=lambda x: x.name)


def _format_size(size_bytes: int) -> str:
    """Format bytes to human readable size."""
    for unit in ["B", "KB", "MB", "GB"]:
        if size_bytes < 1024.0:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.1f} TB"


def _collect_upload_info(
    media_folders: list[Path],
    episode_filter: int | None,
    r2_uploader: R2Uploader | None,
    upload_r2: bool = False,
) -> dict:
    """Collect information about what will be uploaded."""
    total_media = len(media_folders)
    total_episodes = 0
    total_segments = 0
    total_files = 0
    total_size = 0

    media_details = []

    for media_folder in media_folders:
        # Load media info
        info_path = media_folder / "_info.json"
        if not info_path.exists():
            continue

        with open(info_path) as f:
            media_data = json.load(f)

        source = get_media_source(media_data.get("media_source", "anilist"))
        media_id, title = source.summary_identity(media_data)
        media_title = title or media_folder.name

        # Collect episodes
        episode_folders = sorted(
            [d for d in media_folder.iterdir() if d.is_dir() and not d.name.startswith("_")]
        )

        episodes_to_upload = []
        for surrogate, episode_folder in enumerate(episode_folders, start=1):
            episode_number = source.episode_number(episode_folder, surrogate)
            if episode_number is None:
                continue

            if episode_filter and episode_number != episode_filter:
                continue

            # Load episode data
            data_path = episode_folder / "_data.json"
            if not data_path.exists():
                continue

            with open(data_path) as f:
                episode_data = json.load(f)

            segments = episode_data.get("segments", [])

            # Count files to upload (only if uploading to R2)
            episode_files = 0
            episode_size = 0
            if upload_r2:
                for segment in segments:
                    for _file_type, filename in segment.get("files", {}).items():
                        if not filename:
                            continue
                        filepath = episode_folder / filename
                        if filepath.exists():
                            episode_files += 1
                            episode_size += filepath.stat().st_size

            episodes_to_upload.append(
                {
                    "number": episode_number,
                    "segments": len(segments),
                    "files": episode_files,
                    "size": episode_size,
                }
            )

            total_episodes += 1
            total_segments += len(segments)
            total_files += episode_files
            total_size += episode_size

        if episodes_to_upload:
            media_details.append(
                {
                    "id": media_id,
                    "title": media_title,
                    "episodes": episodes_to_upload,
                }
            )

    return {
        "total_media": total_media,
        "total_episodes": total_episodes,
        "total_segments": total_segments,
        "total_files": total_files,
        "total_size": total_size,
        "media_details": media_details,
    }


def _display_upload_summary(
    info: dict, target: str, storage_target: str, upload_r2: bool = False
) -> None:
    """Display a summary of what will be uploaded."""
    color = "red" if target == "prod" else ("cyan" if target == "dev" else "green")

    console.print(f"\n[bold {color}]{'=' * 60}[/bold {color}]")
    console.print(f"[bold {color}]UPLOAD SUMMARY[/bold {color}]")
    console.print(f"[bold {color}]{'=' * 60}[/bold {color}]")

    console.print(f"\n[bold]Media:[/bold] {info['total_media']}")
    console.print(f"[bold]Episodes:[/bold] {info['total_episodes']}")
    console.print(f"[bold]Segments:[/bold] {info['total_segments']}")
    console.print(f"[bold]API target:[/bold] {target}")
    console.print(f"[bold]Storage target:[/bold] {storage_target}")

    if storage_target == "r2" and upload_r2:
        console.print(f"[bold]Files to upload:[/bold] {info['total_files']}")
        console.print(f"[bold]Total size:[/bold] {_format_size(info['total_size'])}")
    elif storage_target == "r2":
        console.print("[dim]R2 upload: [bold]SKIPPED[/bold] (--upload-r2 not specified)[/dim]")
    else:
        console.print("[dim]Files to R2: [bold]N/A[/bold] (storage target is local)[/dim]")

    for media in info["media_details"]:
        console.print(f"\n[cyan]▸ {media['title']} (ID: {media['id']})[/cyan]")
        for ep in media["episodes"]:
            size_str = _format_size(ep["size"])
            console.print(
                f"  [dim]E{ep['number']:02d}[/dim] - {ep['segments']} segments, "
                f"{ep['files']} files, {size_str}"
            )

    console.print(f"\n[bold {color}]{'=' * 60}[/bold {color}]\n")


def upload_all(
    output_path: str,
    episode: int | None = None,
    env: str = "local",
    storage_target: str = "local",
    dry_run: bool = True,
    upload_r2: bool = False,
    update_info_only: bool = False,
    skip_confirm: bool = False,
) -> None:
    """Upload all media from the output directory.

    Args:
        output_path: Path to media folder (e.g., /path/to/output/12345)
        episode: Optional episode number to filter upload
        env: API environment to upload to (local, dev, or prod). Default is local.
        storage_target: Storage target for files ("local" or "r2").
        dry_run: Show what would be uploaded without actually uploading. Default is True.
        upload_r2: Actually upload files to R2. Only used when storage_target="r2".
        update_info_only: Only update media info (skip episodes and segments)
    """
    media_folder = Path(output_path).resolve()

    if not media_folder.exists():
        console.print(f"[red]Media folder does not exist: {media_folder}[/red]")
        return

    # Verify it's a valid media folder (has _info.json)
    if not (media_folder / "_info.json").exists():
        console.print(f"[red]Invalid media folder (missing _info.json): {media_folder}[/red]")
        return

    if env not in ("local", "dev", "prod"):
        console.print(f"[red]Invalid environment: {env}. Must be 'local', 'dev', or 'prod'[/red]")
        return

    if storage_target not in ("local", "r2"):
        console.print(
            f"[red]Invalid storage target: {storage_target}. Must be 'local' or 'r2'[/red]"
        )
        return

    if storage_target == "local" and upload_r2:
        console.print("[red]Invalid combination: --upload-r2 requires --storage r2.[/red]")
        return

    # Load config
    config = Config.from_env(env=env)
    if not config.validate(storage_target=storage_target, upload_r2=upload_r2):
        return

    # Display target
    config.display_target()

    # Check if episode filter exists
    if episode:
        episode_folder = media_folder / str(episode)
        if not episode_folder.exists() or not (episode_folder / "_data.json").exists():
            console.print(f"[yellow]No episode {episode} found in media folder[/yellow]")
            return

    # Collect and display upload info
    # Only initialize R2Uploader when we'll actually use it
    r2 = R2Uploader(config) if upload_r2 else None
    upload_info = _collect_upload_info([media_folder], episode, r2, upload_r2)

    if upload_info["total_files"] == 0 and not dry_run and storage_target == "r2" and upload_r2:
        console.print("[yellow]All files already uploaded. Nothing to do.[/yellow]")
        return

    _display_upload_summary(upload_info, config.target, storage_target, upload_r2)

    # Safety check for prod
    if config.is_prod and not dry_run and not skip_confirm:
        console.print("[bold red] Type 'yes' to confirm upload to PRODUCTION: [/bold red]", end="")
        if input() != "yes":
            console.print("[yellow]Upload cancelled.[/yellow]")
            return

    uploader = NadeshikoUploader(
        config,
        dry_run=dry_run,
        storage_target=storage_target,
        upload_r2=upload_r2,
        update_info_only=update_info_only,
    )

    # Upload the media
    success = uploader.upload_media(media_folder, episode_filter=episode)
    if success:
        console.print("\n[green]Upload complete![/green]")
    else:
        console.print("\n[yellow]Upload completed with errors (will retry next run).[/yellow]")
