"""Nadeshiko segment uploader.

Uploads media segments generated by media-sub-splitter to:
- Nadeshiko API (metadata)
- Cloudflare R2 (media files, optional - use --upload-r2 flag)

By default, only the backend is updated without uploading files to R2.
"""

import datetime as dt
import json
import os
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from datetime import timedelta
from enum import Enum
from pathlib import Path

import boto3
from botocore.config import Config as BotoConfig
from botocore.exceptions import ClientError
from dotenv import load_dotenv
from rich.console import Console
from rich.progress import Progress, TaskID

load_dotenv(override=True)

console = Console()

# Nadeshiko SDK imports — must come after load_dotenv()
from nadeshiko_internal import Nadeshiko  # noqa: E402
from nadeshiko_internal.api.media import (  # noqa: E402
    create_episode,
    create_media,
    create_segments_batch,
    get_episode,
    list_media,
    update_media,
)
from nadeshiko_internal.models import (  # noqa: E402
    CharacterInput,
    CharacterInputRole,
    CharacterInputSeiyuu,
    ContentRating,
    CreateSegmentsBatchResponse201,
    EpisodeCreateRequest,
    Error400,
    Error401,
    Error403,
    Error404,
    Error409,
    Error429,
    Error500,
    ExternalId,
    MediaCreateRequest,
    MediaCreateRequestCategory,
    MediaCreateRequestStorage,
    MediaListResponse,
    MediaUpdateRequest,
    MediaUpdateRequestStorage,
    SegmentBatchCreateRequest,
    SegmentCreateRequest,
    SegmentCreateRequestStorage,
    SegmentCreateRequestTextEn,
    SegmentCreateRequestTextEs,
    SegmentCreateRequestTextJa,
)
from nadeshiko_internal.types import UNSET  # noqa: E402

# All SDK error types for isinstance checks
API_ERROR_TYPES = (Error400, Error401, Error403, Error404, Error409, Error429, Error500)


def _validate_sdk_contract() -> None:
    """Fail fast when an older SDK shape is installed."""
    contract_checks = {
        "MediaListResponse": (MediaListResponse, {"media", "pagination"}),
        "SegmentCreateRequest": (
            SegmentCreateRequest,
            {"start_time_ms", "end_time_ms", "content_rating", "rating_analysis", "pos_analysis"},
        ),
        "SegmentBatchCreateRequest": (
            SegmentBatchCreateRequest,
            {"segments"},
        ),
    }
    missing: dict[str, list[str]] = {}
    for name, (model, required_fields) in contract_checks.items():
        present = set(getattr(model, "__annotations__", {}).keys())
        absent = sorted(required_fields - present)
        if absent:
            missing[name] = absent

    if missing:
        details = ", ".join(f"{name}: {fields}" for name, fields in missing.items())
        raise RuntimeError(
            "Unsupported nadeshiko-internal-sdk contract; expected 1.4.3+ fields. "
            f"Missing: {details}"
        )


class SegmentResult(Enum):
    """Result status for segment creation."""
    OK = "OK"
    DUPLICATE = "DUPLICATE"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"


# R2 S3-compatible endpoint
# R2 S3-compatible endpoint
R2_ENDPOINT_TEMPLATE = "https://{account_id}.r2.cloudflarestorage.com"

# Pattern to detect raw R2 URLs that need to be replaced with CDN URLs
RAW_R2_PATTERN = "https://{account_id}.r2.cloudflarestorage.com"


def normalize_r2_url(url: str, r2_public_url: str) -> str:
    """Convert raw R2 URL to CDN URL if needed.

    Args:
        url: The URL to normalize (may be raw R2 or already CDN)
        r2_public_url: The CDN base URL (e.g., https://cdn.nadeshiko.co)

    Returns:
        The normalized URL using the CDN domain
    """
    if not url:
        return url

    # If URL is already using the CDN domain, return as-is
    if url.startswith(r2_public_url):
        return url

    # If URL is a raw R2 URL, extract the path and prepend CDN domain
    if ".r2.cloudflarestorage.com/" in url:
        # Extract path after the bucket/domain
        parts = url.split("/media/", 1)
        if len(parts) == 2:
            return f"{r2_public_url}/media/{parts[1]}"

    return url


IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".webp")


def _parse_iso_date(date_str: str | None):
    """Parse an ISO date/datetime string to a date, or return UNSET."""
    if not date_str:
        return UNSET
    try:
        normalized = date_str.strip()
        if normalized.endswith("Z"):
            normalized = f"{normalized[:-1]}+00:00"
        parsed = dt.datetime.fromisoformat(normalized)
        return parsed.date()
    except (ValueError, TypeError):
        return UNSET


def _find_image_file(folder: Path, prefix: str) -> Path | None:
    """Find an image file like cover.jpg, cover.png, etc. in a folder."""
    for ext in IMAGE_EXTENSIONS:
        path = folder / f"{prefix}{ext}"
        if path.exists():
            return path
    return None


def _find_japanese_stream(audio_streams: list[dict]) -> dict | None:
    """Find a Japanese audio stream from a list of audio stream dicts."""
    for stream in audio_streams:
        lang = stream.get("tags", {}).get("language", "").lower()
        if lang in ("jpn", "ja", "japanese"):
            return stream
    return None


@dataclass
class Config:
    """Configuration from environment variables."""

    nadeshiko_api_key: str
    nadeshiko_base_url: str
    r2_account_id: str
    r2_access_key_id: str
    r2_secret_access_key: str
    r2_bucket: str
    r2_public_url: str
    target: str = "local"
    is_prod: bool = False

    @classmethod
    def from_env(cls, env: str = "local") -> "Config":
        if env not in ("local", "dev", "prod"):
            raise ValueError(f"Invalid environment: {env}")

        def _first_set(*names: str, default: str = "") -> str:
            for name in names:
                value = os.getenv(name)
                if value:
                    return value
            return default

        # R2 config is shared across all environments
        r2_kwargs = {
            "r2_account_id": os.getenv("R2_ACCOUNT_ID", ""),
            "r2_access_key_id": os.getenv("R2_ACCESS_KEY_ID", ""),
            "r2_secret_access_key": os.getenv("R2_SECRET_ACCESS_KEY", ""),
            "r2_bucket": os.getenv("R2_BUCKET", "nadeshiko-segments"),
            "r2_public_url": os.getenv("R2_PUBLIC_URL", ""),
        }

        env_config = {
            "local": {
                "nadeshiko_api_key": _first_set("NADESHIKO_LOCAL_API_KEY", "NADESHIKO_API_KEY"),
                "nadeshiko_base_url": _first_set(
                    "NADESHIKO_LOCAL_BASE_URL", "NADESHIKO_BASE_URL",
                    default="http://localhost:5000",
                ),
                "is_prod": False,
            },
            "dev": {
                "nadeshiko_api_key": _first_set("NADESHIKO_DEV_API_KEY", "NADESHIKO_API_KEY"),
                "nadeshiko_base_url": _first_set(
                    "NADESHIKO_DEV_BASE_URL", default="https://api-dev.nadeshiko.co",
                ),
                "is_prod": False,
            },
            "prod": {
                "nadeshiko_api_key": os.getenv("NADESHIKO_PROD_API_KEY", ""),
                "nadeshiko_base_url": os.getenv(
                    "NADESHIKO_PROD_BASE_URL", "https://api.nadeshiko.co"
                ),
                "is_prod": True,
            },
        }

        return cls(**env_config[env], **r2_kwargs, target=env)

    def validate(self, storage_target: str = "local", upload_r2: bool = False) -> bool:
        """Check that required config is present.

        Args:
            storage_target: Where media files should be served from ("local" or "r2").
            upload_r2: Whether files will be uploaded to R2. If False, R2 credentials are optional.
        """
        missing = []
        if not self.nadeshiko_api_key:
            if self.target == "local":
                missing.append("NADESHIKO_LOCAL_API_KEY (or NADESHIKO_API_KEY)")
            elif self.target == "dev":
                missing.append("NADESHIKO_DEV_API_KEY (or NADESHIKO_API_KEY)")
            else:
                missing.append("NADESHIKO_PROD_API_KEY")

        # R2 credentials are required only when files are uploaded to R2.
        needs_r2 = upload_r2

        if needs_r2:
            if not self.r2_public_url:
                missing.append("R2_PUBLIC_URL")
            if not self.r2_account_id:
                missing.append("R2_ACCOUNT_ID")
            if not self.r2_access_key_id:
                missing.append("R2_ACCESS_KEY_ID")
            if not self.r2_secret_access_key:
                missing.append("R2_SECRET_ACCESS_KEY")
            if not self.r2_bucket:
                missing.append("R2_BUCKET")

        if missing:
            console.print(f"[red]Missing required env vars: {', '.join(missing)}[/red]")
            return False
        return True

    def display_target(self) -> None:
        """Display the upload target with appropriate styling."""
        if self.is_prod:
            console.print(
                "\n[bold red on white] TARGET: PRODUCTION [/bold red on white]\n"
                "[bold red] This will upload to PRODUCTION! [/bold red]"
            )
        elif self.target == "dev":
            console.print(
                "\n[bold cyan] TARGET: DEV [/bold cyan]\n"
                f"[dim] API: {self.nadeshiko_base_url}[/dim]"
            )
        else:
            console.print(
                "\n[bold green] TARGET: LOCAL [/bold green]\n"
                f"[dim] API: {self.nadeshiko_base_url}[/dim]"
            )


@dataclass
class SegmentData:
    """Segment data from _data.json."""

    segment_hash: str
    segment_index: int
    start_ms: int
    end_ms: int
    duration_ms: int
    content_ja: str
    content_es: str | None
    content_en: str | None
    is_mt_es: bool
    is_mt_en: bool
    actor_ja: str | None
    actor_es: str | None
    actor_en: str | None
    files: dict[str, str]  # audio, screenshot, video filenames
    subtitles: dict  # ja, es, en subtitle details
    content_rating: str
    content_analysis: dict
    pos_analysis: dict


@dataclass
class EpisodeData:
    """Episode data from _data.json."""

    number: int
    duration_ms: int
    total_segments: int
    segments: list[SegmentData]
    ignored_segments: list[dict]


@dataclass
class MediaInfo:
    """Media info from _info.json."""

    anilist_id: int
    japanese_name: str | None
    english_name: str | None
    romaji_name: str
    airing_format: str
    airing_status: str
    genres: list[str]
    version: str
    hash_salt: str
    cover_url: str | None
    banner_url: str | None
    start_date: str | None  # ISO format date string (YYYY-MM-DD)
    end_date: str | None  # ISO format date string (YYYY-MM-DD)
    characters: list[dict] | None = None
    studio: str | None = None
    season_name: str | None = None
    season_year: int | None = None


class R2Uploader:
    """Handles file uploads to Cloudflare R2."""

    def __init__(self, config: Config):
        self.config = config
        self.endpoint = R2_ENDPOINT_TEMPLATE.format(account_id=config.r2_account_id)
        self.bucket = config.r2_bucket
        self.public_url = config.r2_public_url

        self.s3_client = boto3.client(
            "s3",
            endpoint_url=self.endpoint,
            aws_access_key_id=config.r2_access_key_id,
            aws_secret_access_key=config.r2_secret_access_key,
            config=BotoConfig(max_pool_connections=50),
        )

    def get_r2_key(self, storage_base_path: str, episode_number: int, filename: str) -> str:
        """Generate R2 object key for a file."""
        return f"{storage_base_path}/{episode_number}/{filename}"

    def upload_file(
        self,
        filepath: Path,
        storage_base_path: str,
        episode_number: int,
        progress: Progress | None = None,
        task_id: TaskID | None = None,
    ) -> str | None:
        """Upload a file to R2 and return its public URL."""
        key = self.get_r2_key(storage_base_path, episode_number, filepath.name)

        try:
            callback = None
            if progress and task_id:
                def callback(bytes_transferred):
                    progress.update(task_id, advance=bytes_transferred)

            self.s3_client.upload_file(
                str(filepath),
                self.bucket,
                key,
                Callback=callback,
            )
            # Return public URL
            return f"{self.public_url}/{key}"
        except ClientError as e:
            console.print(f"[red]Error uploading {filepath.name}: {e}[/red]")
            return None

    def file_exists(self, storage_base_path: str, episode_number: int, filename: str) -> bool:
        """Check if a file already exists in R2."""
        key = self.get_r2_key(storage_base_path, episode_number, filename)
        try:
            self.s3_client.head_object(Bucket=self.bucket, Key=key)
            return True
        except ClientError:
            return False

    def list_existing_files(self, storage_base_path: str, episode_number: int) -> set[str]:
        """List all existing filenames in an episode's R2 prefix in a single call."""
        prefix = f"{storage_base_path}/{episode_number}/"
        existing: set[str] = set()
        try:
            paginator = self.s3_client.get_paginator("list_objects_v2")
            for page in paginator.paginate(Bucket=self.bucket, Prefix=prefix):
                for obj in page.get("Contents", []):
                    existing.add(obj["Key"].split("/")[-1])
        except ClientError as e:
            console.print(f"[yellow]Warning: could not list R2 prefix {prefix}: {e}[/yellow]")
        return existing

    def get_media_r2_key(self, storage_base_path: str, filename: str) -> str:
        """Generate R2 object key for a media-level file (cover/banner)."""
        return f"{storage_base_path}/{filename}"

    def upload_media_file(self, filepath: Path, storage_base_path: str) -> str | None:
        """Upload a media-level file (cover/banner) to R2 and return its public URL."""
        key = self.get_media_r2_key(storage_base_path, filepath.name)

        try:
            self.s3_client.upload_file(str(filepath), self.bucket, key)
            return f"{self.public_url}/{key}"
        except ClientError as e:
            console.print(f"[red]Error uploading {filepath.name}: {e}[/red]")
            return None

    def media_file_exists(self, storage_base_path: str, filename: str) -> bool:
        """Check if a media-level file already exists in R2."""
        key = self.get_media_r2_key(storage_base_path, filename)
        try:
            self.s3_client.head_object(Bucket=self.bucket, Key=key)
            return True
        except ClientError:
            return False

    def get_media_file_url(self, storage_base_path: str, filename: str) -> str:
        """Get the public URL for a media-level file."""
        key = self.get_media_r2_key(storage_base_path, filename)
        return f"{self.public_url}/{key}"


# Batch segment creation constants
BATCH_SIZE = 900  # Margin below 1000 API limit
MAX_BODY_BYTES = 9 * 1024 * 1024  # Margin below 10 MB API limit
_RATE_LIMIT_WAIT_SECONDS = 60  # Fixed 1 minute wait for rate limits


class UploadHistory:
    """Tracks which media/episodes have been successfully uploaded per environment.

    History is stored as a JSON file at {root_dir}/_upload_history_{env}.json.
    Structure: { "<media_id>": { "episodes": [1, 2, 3], "completed": false } }
    A media is "completed" when all its episodes have been uploaded successfully.
    """

    def __init__(self, root_dir: Path, env: str):
        self.path = root_dir / f"_upload_history_{env}.json"
        self._data: dict[str, dict] = {}
        self._load()

    def _load(self) -> None:
        if self.path.exists():
            with open(self.path) as f:
                self._data = json.load(f)

    def _save(self) -> None:
        with open(self.path, "w") as f:
            json.dump(self._data, f, indent=2, sort_keys=True)

    def is_media_complete(self, media_id: str) -> bool:
        return self._data.get(media_id, {}).get("completed", False)

    def is_episode_done(self, media_id: str, episode: int) -> bool:
        return episode in self._data.get(media_id, {}).get("episodes", [])

    def mark_episode_done(self, media_id: str, episode: int) -> None:
        entry = self._data.setdefault(media_id, {"episodes": [], "completed": False})
        if episode not in entry["episodes"]:
            entry["episodes"].append(episode)
            entry["episodes"].sort()
        self._save()

    def mark_media_complete(self, media_id: str) -> None:
        entry = self._data.setdefault(media_id, {"episodes": [], "completed": False})
        entry["completed"] = True
        self._save()


class NadeshikoUploader:
    """Handles uploading to Nadeshiko API and R2."""

    # Maximum content length for segments (characters)
    MAX_CONTENT_LENGTH = 500

    def __init__(
        self,
        config: Config,
        dry_run: bool = False,
        storage_target: str = "local",
        upload_r2: bool = False,
        update_info_only: bool = False,
        history: UploadHistory | None = None,
    ):
        _validate_sdk_contract()
        self.config = config
        self.dry_run = dry_run
        self.storage_target = storage_target
        self.upload_r2 = upload_r2
        self.update_info_only = update_info_only
        self.history = history
        # Only initialize R2Uploader when we'll actually use it
        self.r2 = R2Uploader(config) if upload_r2 else None

        self.api_client = Nadeshiko(
            token=config.nadeshiko_api_key,
            base_url=config.nadeshiko_base_url,
        )
        self.ErrorTypes = API_ERROR_TYPES
        self._console_lock = threading.Lock()
        self.stats = {
            "total": 0,
            "uploaded": 0,
            "duplicated": 0,
            "skipped_no_hash": 0,
            "skipped_no_translations": 0,
            "skipped_too_long": 0,
            "skipped_constraint": 0,
            "failed": 0,
            "errors_by_status": {},  # Track errors by HTTP status code
        }

        if dry_run:
            console.print(
                "[cyan]Running in DRY-RUN mode. Use --apply to perform actual uploads.[/cyan]"
            )

    def _ms_to_hmsff(self, milliseconds: int) -> str:
        """Convert milliseconds to H:MM:SS.ffffff format."""
        td = timedelta(milliseconds=milliseconds)
        total_seconds = td.total_seconds()
        hours = int(total_seconds // 3600)
        minutes = int((total_seconds % 3600) // 60)
        seconds = total_seconds % 60
        return f"{hours}:{minutes:02d}:{seconds:06f}"

    def _get_error_attr(self, error: object, attr_name: str):
        """Safely read SDK error attributes that may raise KeyError."""
        try:
            val = getattr(error, attr_name)
            # Typed status enums (e.g. Error400Status) → unwrap to int
            if attr_name == "status" and hasattr(val, "value"):
                return val.value
            return val
        except (KeyError, AttributeError):
            return None

    def _is_api_error(self, value: object) -> bool:
        """Check whether a response is an SDK error (public or internal)."""
        return isinstance(value, self.ErrorTypes)

    def _is_auth_error(self, error: object) -> bool:
        """Check for authentication errors returned by the API."""
        return isinstance(error, Error401)

    def _print_api_error(self, error: object) -> None:
        """Print standard API error details."""
        for attr_name in ["detail", "status", "code", "title", "errors"]:
            value = self._get_error_attr(error, attr_name)
            if value:
                self._print(f"  [red]{attr_name.capitalize()}:[/red] {value}")

    def _is_rate_limit_error(self, error: object) -> bool:
        """Check if an error is a 429 rate limit error."""
        return isinstance(error, Error429)

    def _is_constraint_error(self, error: object) -> bool:
        """Check if an error is a payload validation error for a specific segment.

        Only HTTP 400 is considered skippable. Other 4xx values (forbidden/not found)
        usually indicate auth or upstream consistency issues that should fail loudly.
        """
        return isinstance(error, Error400)

    def _get_retry_after_seconds(self, error: object) -> int:
        """Get the retry-after seconds from a rate limit error.

        We use a fixed 60-second wait for all rate limit errors to keep
        things simple and reliable.
        """
        return _RATE_LIMIT_WAIT_SECONDS

    def _should_skip_segment(self, segment: SegmentData) -> tuple[bool, str]:
        """Check if a segment should be skipped and return (skip, reason)."""
        # Check if segment has a valid hash
        if not segment.segment_hash:
            return True, "no segment hash"

        # Check if segment has all three translations
        if not segment.content_es:
            return True, "no Spanish translation"
        if not segment.content_en:
            return True, "no English translation"

        # Check if any content field is too long
        for field, value in [
            ("ja", segment.content_ja),
            ("en", segment.content_en),
            ("es", segment.content_es),
        ]:
            if value and len(value) > self.MAX_CONTENT_LENGTH:
                return True, f"content too long ({field}: {len(value)} > {self.MAX_CONTENT_LENGTH})"

        return False, ""

    def _segment_content_rating(self, segment: SegmentData):
        """Convert text content rating to SDK enum, or UNSET when unknown."""
        rating = (segment.content_rating or "").strip().upper()
        if not rating:
            return UNSET
        try:
            return ContentRating(rating)
        except ValueError:
            return UNSET

    def _coerce_int(self, value: object) -> int | None:
        """Coerce values from _info.json into an integer ID."""
        if isinstance(value, bool):
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, str):
            stripped = value.strip()
            if stripped and stripped.isdigit():
                return int(stripped)
        return None

    def _parse_character_role(self, value: object) -> CharacterInputRole:
        """Parse AniList role values from _info.json into SDK enum values."""
        if isinstance(value, CharacterInputRole):
            return value
        role_text = str(value or "").upper()
        for role in CharacterInputRole:
            if role.value in role_text:
                return role
        return CharacterInputRole.SUPPORTING

    def _build_character_inputs(self, media_info: MediaInfo) -> list[CharacterInput] | None:
        """Build SDK CharacterInput objects from _info.json character records.

        Returns None when characters were absent in _info.json so we don't
        accidentally overwrite server-side character data.

        Currently disabled - character upload is temporarily disabled.
        """
        return None

    def _print(self, *args, **kwargs) -> None:
        """Thread-safe console print."""
        with self._console_lock:
            console.print(*args, **kwargs)

    def _upload_media_images(self, media_folder: Path, storage_base_path: str) -> None:
        """Upload cover and banner images to R2 if they exist locally."""
        if not self.upload_r2 or not self.r2:
            return

        for prefix in ("cover", "banner"):
            image_path = _find_image_file(media_folder, prefix)
            if not image_path:
                continue
            if not self.r2.media_file_exists(storage_base_path, image_path.name):
                self.r2.upload_media_file(image_path, storage_base_path)
                console.print(f"[green]Uploaded {prefix}: {image_path.name}[/green]")
            else:
                console.print(
                    f"[dim]{prefix.capitalize()} already uploaded: {image_path.name}[/dim]"
                )

    def _update_media_info(
        self, existing_media, media_info: MediaInfo,
        media_folder: Path, storage_base_path: str = "",
    ) -> int | None:
        """Update existing media with storage backend and other info."""
        if self.dry_run:
            console.print(f"[cyan][DRY RUN] Would update media: {existing_media.id}[/cyan]")
            return existing_media.id

        console.print(f"[cyan]Updating media info: {existing_media.id}[/cyan]")

        storage = (
            MediaUpdateRequestStorage.R2
            if self.storage_target == "r2"
            else MediaUpdateRequestStorage.LOCAL
        )

        self._upload_media_images(media_folder, storage_base_path)

        start_date = _parse_iso_date(media_info.start_date)
        end_date = _parse_iso_date(media_info.end_date)

        # Build update request with only fields that are set
        request = MediaUpdateRequest()
        request.storage = storage
        request.external_ids = ExternalId(anilist=str(media_info.anilist_id))
        if start_date is not UNSET:
            request.start_date = start_date
        if end_date is not UNSET:
            request.end_date = end_date
        if media_info.studio:
            request.studio = media_info.studio
        if media_info.season_name:
            request.season_name = media_info.season_name
        if media_info.season_year is not None:
            request.season_year = media_info.season_year
        if media_info.hash_salt:
            request.hash_salt = media_info.hash_salt
        if media_info.version:
            request.version = media_info.version
        character_inputs = self._build_character_inputs(media_info)
        if character_inputs is not None:
            request.characters = character_inputs
        if storage_base_path:
            request.storage_base_path = storage_base_path

        update_result = update_media.sync(
            client=self.api_client, id=existing_media.id, body=request
        )

        if update_result and not self._is_api_error(update_result):
            console.print(f"[green]Updated media: {existing_media.id}[/green]")
            return existing_media.id

        if self._is_api_error(update_result):
            console.print("\n[red]Failed to update media:[/red]")
            self._print_api_error(update_result)
        else:
            console.print("[red]Failed to update media: Unknown error[/red]")
        return existing_media.id  # Return ID anyway if update failed

    def _load_media_info(self, media_folder: Path) -> MediaInfo | None:
        """Load _info.json from a media folder."""
        info_path = media_folder / "_info.json"
        if not info_path.exists():
            console.print(f"[yellow]No _info.json found in {media_folder}[/yellow]")
            return None

        with open(info_path) as f:
            data = json.load(f)

        return MediaInfo(
            anilist_id=data.get("anilist_id", data.get("id")),
            japanese_name=data.get("japanese_name"),
            english_name=data.get("english_name"),
            romaji_name=data.get("romaji_name"),
            airing_format=data.get("airing_format", "TV"),
            airing_status=data.get("airing_status", "FINISHED"),
            genres=data.get("genres", []),
            version=data.get("version", "1.0"),
            hash_salt=data.get("hash_salt", ""),
            cover_url=data.get("cover_url"),
            banner_url=data.get("banner_url"),
            start_date=data.get("start_date"),
            end_date=data.get("end_date"),
            characters=data.get("characters"),
            studio=data.get("studio"),
            season_name=data.get("season", {}).get("name"),
            season_year=data.get("season", {}).get("year"),
        )

    @staticmethod
    def _load_nsfw_lookup(media_folder: Path) -> dict[str, dict]:
        """Load _nsfw_results/results.json and return a flat {hashed_id: result} lookup."""
        results_path = media_folder / "_nsfw_results" / "results.json"
        if not results_path.exists():
            return {}
        with open(results_path) as f:
            data = json.load(f)
        lookup: dict[str, dict] = {}
        for ep_data in data.values():
            for hashed_id, result in ep_data.items():
                lookup[hashed_id] = result
        return lookup

    def _load_episode_data(
        self, episode_folder: Path, nsfw_lookup: dict[str, dict] | None = None
    ) -> EpisodeData | None:
        """Load _data.json from an episode folder."""
        data_path = episode_folder / "_data.json"
        if not data_path.exists():
            console.print(f"[yellow]No _data.json found in {episode_folder}[/yellow]")
            return None

        with open(data_path) as f:
            data = json.load(f)

        metadata = data.get("metadata", {})
        segments = []
        for s in data.get("segments", []):
            seg_hash = s.get("segment_hash", "")
            nsfw = (nsfw_lookup or {}).get(seg_hash, {})

            content_rating = nsfw.get("content_rating") or s.get("content_rating")
            if not content_rating:
                console.print(
                    f"[red]Missing content_rating for segment {seg_hash} in {episode_folder}[/red]"
                )
                return None

            if nsfw:
                content_analysis = {"scores": nsfw["scores"], "tags": nsfw["tags"]}
            else:
                content_analysis = s.get("content_analysis")
            if not content_analysis:
                console.print(
                    f"[red]Missing content_analysis for segment {seg_hash} in {episode_folder}[/red]"
                )
                return None

            pos_analysis = s.get("pos_analysis")
            if not pos_analysis:
                console.print(
                    f"[red]Missing pos_analysis for segment {seg_hash} in {episode_folder}[/red]"
                )
                return None

            segments.append(SegmentData(
                segment_hash=seg_hash,
                segment_index=s.get("segment_index", 0),
                start_ms=s.get("start_ms", 0),
                end_ms=s.get("end_ms", 0),
                duration_ms=s.get("duration_ms", 0),
                content_ja=s.get("content_ja", ""),
                content_es=s.get("content_es"),
                content_en=s.get("content_en"),
                is_mt_es=s.get("is_mt_es", False),
                is_mt_en=s.get("is_mt_en", False),
                actor_ja=s.get("actor_ja"),
                actor_es=s.get("actor_es"),
                actor_en=s.get("actor_en"),
                files=s.get("files", {}),
                subtitles=s.get("subtitles", {}),
                content_rating=content_rating,
                content_analysis=content_analysis,
                pos_analysis=pos_analysis,
            ))

        return EpisodeData(
            number=metadata.get("number", 0),
            duration_ms=metadata.get("duration_ms", 0),
            total_segments=metadata.get("total_segments", 0),
            segments=segments,
            ignored_segments=data.get("ignored_segments", []),
        )

    def _get_or_create_media(self, media_info: MediaInfo, media_folder: Path) -> int | None:
        """Get existing media or create new one. Returns media ID."""
        if self.dry_run or not self.api_client:
            console.print(
                f"[cyan][DRY RUN] Would get/create media: {media_info.romaji_name}[/cyan]"
            )
            return media_info.anilist_id

        # Try to find existing media by anilist_id - use search endpoint
        try:
            result = list_media.sync(client=self.api_client)
        except Exception as e:
            console.print(f"[red]Failed to list media: {type(e).__name__}: {e}[/red]")
            return None

        if self._is_api_error(result):
            if self._is_auth_error(result):
                console.print(
                    "[red]Authentication failed while listing media. "
                    "Check your API key for the selected target (local/dev/prod).[/red]"
                )
            else:
                console.print("\n[red]Failed to list media:[/red]")
                self._print_api_error(result)
            return None

        existing_media = None
        if result and not self._is_api_error(result):
            # Search through results for matching anilist_id via external_ids
            media_items = result.media
            for media in media_items:
                ext_ids = getattr(media, "external_ids", UNSET)
                anilist_id = getattr(ext_ids, "anilist", None) if ext_ids is not UNSET else None
                if str(anilist_id) == str(media_info.anilist_id):
                    console.print(f"[green]Found existing media: {media.id}[/green]")
                    existing_media = media
                    break

        # If media exists, always sync media info (including characters).
        # `--update-info` only controls whether episodes/segments are skipped later.
        if existing_media:
            media_id = self._update_media_info(
                existing_media, media_info, media_folder,
                storage_base_path=f"media/{media_info.anilist_id}",
            )
            return media_id if media_id is not None else existing_media.id

        # Determine storage backend
        storage = (
            MediaCreateRequestStorage.R2
            if self.storage_target == "r2"
            else MediaCreateRequestStorage.LOCAL
        )

        storage_base_path = f"media/{media_info.anilist_id}"
        self._upload_media_images(media_folder, storage_base_path)

        if not _find_image_file(media_folder, "cover"):
            console.print(
                "[red]Error: cover image is required but not found. "
                "Add cover.jpg/png/webp to the media folder[/red]"
            )
            return None

        start_date = _parse_iso_date(media_info.start_date)
        if start_date is UNSET:
            start_date = dt.date(1970, 1, 1)
        end_date = _parse_iso_date(media_info.end_date)

        # Validate required fields
        if not media_info.studio:
            console.print("[red]Error: studio is required but not found in _info.json[/red]")
            return None
        if not media_info.season_name:
            console.print("[red]Error: season.name is required but not found in _info.json[/red]")
            return None
        if media_info.season_year is None:
            console.print("[red]Error: season.year is required but not found in _info.json[/red]")
            return None

        character_inputs = self._build_character_inputs(media_info)

        # Create new media
        request = MediaCreateRequest(
            name_ja=media_info.japanese_name or media_info.romaji_name,
            name_romaji=media_info.romaji_name,
            name_en=media_info.english_name or media_info.romaji_name,
            airing_format=media_info.airing_format,
            airing_status=media_info.airing_status,
            genres=media_info.genres,
            category=MediaCreateRequestCategory.ANIME,
            version=media_info.version,
            studio=media_info.studio,
            season_name=media_info.season_name,
            season_year=media_info.season_year,
            hash_salt=media_info.hash_salt,
            storage=storage,
            start_date=start_date,
            end_date=end_date,
            external_ids=ExternalId(anilist=str(media_info.anilist_id)),
            characters=character_inputs if character_inputs is not None else UNSET,
            storage_base_path=storage_base_path,
        )

        create_result = create_media.sync(client=self.api_client, body=request)

        if create_result and not self._is_api_error(create_result):
            console.print(f"[green]Created new media: {create_result.id}[/green]")
            return create_result.id

        # On 409 (e.g. duplicate seiyuu), retry without characters — backend should upsert seiyuu
        if isinstance(create_result, Error409) and character_inputs:
            console.print(
                "[yellow]Warning: media creation returned 409 (possibly duplicate seiyuu). "
                "Retrying without characters...[/yellow]"
            )
            retry_request = MediaCreateRequest(
                name_ja=request.name_ja,
                name_romaji=request.name_romaji,
                name_en=request.name_en,
                airing_format=request.airing_format,
                airing_status=request.airing_status,
                genres=request.genres,
                category=request.category,
                version=request.version,
                studio=request.studio,
                season_name=request.season_name,
                season_year=request.season_year,
                hash_salt=request.hash_salt,
                storage=request.storage,
                start_date=request.start_date,
                end_date=request.end_date,
                external_ids=request.external_ids,
                storage_base_path=request.storage_base_path,
            )
            create_result = create_media.sync(client=self.api_client, body=retry_request)
            if create_result and not self._is_api_error(create_result):
                console.print(f"[green]Created new media (without characters): {create_result.id}[/green]")
                return create_result.id

        if self._is_api_error(create_result):
            console.print("\n[red]Failed to create media:[/red]")
            self._print_api_error(create_result)
        else:
            console.print("[red]Failed to create media: Unknown error[/red]")
            console.print(f"[dim]Result type: {type(create_result)}[/dim]")
            console.print(f"[dim]Result: {create_result}[/dim]")
        return None

    def _get_or_create_episode(self, media_id: int, episode_data: EpisodeData) -> bool:
        """Get existing episode or create new one."""
        if self.dry_run or not self.api_client:
            console.print(
                f"[cyan][DRY RUN] Would get/create episode: E{episode_data.number}[/cyan]"
            )
            return True

        # Try to find existing episode
        try:
            result = get_episode.sync(
                client=self.api_client, media_id=media_id, episode_number=episode_data.number
            )
        except Exception as e:
            console.print(
                f"[red]Failed to check episode E{episode_data.number}:"
                f" {type(e).__name__}: {e}[/red]"
            )
            return False

        if result and not self._is_api_error(result):
            console.print(f"[green]Found existing episode: E{episode_data.number}[/green]")
            return True

        if self._is_api_error(result):
            status = self._get_error_attr(result, "status")
            if self._is_auth_error(result):
                console.print(
                    "[red]Authentication failed while checking episodes. "
                    "Check your API key for the selected target (local/dev/prod).[/red]"
                )
                return False
            if status != 404:
                console.print(f"\n[red]Failed to check episode E{episode_data.number}:[/red]")
                self._print_api_error(result)
                return False

        # Create new episode
        request = EpisodeCreateRequest(episode_number=episode_data.number)
        create_result = create_episode.sync(
            client=self.api_client, media_id=media_id, body=request
        )

        if create_result and not self._is_api_error(create_result):
            console.print(f"[green]Created new episode: E{episode_data.number}[/green]")
            return True

        if self._is_api_error(create_result):
            console.print("\n[red]Failed to create episode:[/red]")
            console.print(f"  [red]Episode:[/red] {episode_data.number}")
            self._print_api_error(create_result)
        else:
            console.print("[red]Failed to create episode: Unknown error[/red]")
            console.print(f"[dim]Result type: {type(create_result)}[/dim]")
            console.print(f"[dim]Result: {create_result}[/dim]")
        return False

    def _build_segment_request(self, segment: SegmentData) -> SegmentCreateRequest:
        """Build a SegmentCreateRequest from a SegmentData."""
        storage = (
            SegmentCreateRequestStorage.R2
            if self.storage_target == "r2"
            else SegmentCreateRequestStorage.LOCAL
        )

        ja = SegmentCreateRequestTextJa(content=segment.content_ja)
        es = (
            SegmentCreateRequestTextEs(
                content=segment.content_es,
                is_machine_translated=segment.is_mt_es,
            )
            if segment.content_es
            else UNSET
        )
        en = (
            SegmentCreateRequestTextEn(
                content=segment.content_en,
                is_machine_translated=segment.is_mt_en,
            )
            if segment.content_en
            else UNSET
        )

        return SegmentCreateRequest(
            position=segment.segment_index,
            start_time_ms=segment.start_ms,
            end_time_ms=segment.end_ms,
            text_ja=ja,
            text_es=es,
            text_en=en,
            content_rating=self._segment_content_rating(segment),
            rating_analysis=segment.content_analysis,
            pos_analysis=segment.pos_analysis,
            storage=storage,
            hashed_id=segment.segment_hash,
        )

    @staticmethod
    def _estimate_batch_size(requests: list[SegmentCreateRequest]) -> int:
        """Estimate the JSON body size of a batch of segment requests."""
        # Use a rough per-segment estimate: marshal the first request to get a
        # representative size, then multiply.  This avoids serialising the
        # whole list just to check the size.
        if not requests:
            return 0
        sample = requests[0].to_dict()
        per_segment = len(json.dumps(sample, ensure_ascii=False))
        # Add ~2 bytes per segment for JSON array commas/brackets + wrapper overhead
        return per_segment * len(requests) + 100

    def _chunk_requests(
        self, requests: list[SegmentCreateRequest],
    ) -> list[list[SegmentCreateRequest]]:
        """Split requests into chunks respecting both count and body-size limits."""
        chunks: list[list[SegmentCreateRequest]] = []
        current: list[SegmentCreateRequest] = []
        current_size = 100  # baseline for JSON wrapper

        for req in requests:
            entry_size = len(json.dumps(req.to_dict(), ensure_ascii=False)) + 2
            would_exceed_size = (current_size + entry_size) > MAX_BODY_BYTES
            would_exceed_count = len(current) >= BATCH_SIZE

            if current and (would_exceed_size or would_exceed_count):
                chunks.append(current)
                current = []
                current_size = 100

            current.append(req)
            current_size += entry_size

        if current:
            chunks.append(current)
        return chunks

    def _create_segments_batch(
        self,
        media_id: int,
        episode_number: int,
        requests: list[SegmentCreateRequest],
        max_retries: int = 3,
    ) -> tuple[int, int, int]:
        """Create segments via the batch API endpoint.

        Returns:
            (created, skipped, failed) counts.
        """
        if not requests:
            return 0, 0, 0

        chunks = self._chunk_requests(requests)
        total_created = 0
        total_skipped = 0
        total_failed = 0

        for chunk_idx, chunk in enumerate(chunks, 1):
            if len(chunks) > 1:
                console.print(
                    f"[dim]  Batch {chunk_idx}/{len(chunks)}"
                    f" ({len(chunk)} segments)...[/dim]"
                )

            body = SegmentBatchCreateRequest(segments=chunk)

            for attempt in range(max_retries):
                try:
                    result = create_segments_batch.sync(
                        client=self.api_client,
                        media_id=media_id,
                        episode_number=episode_number,
                        body=body,
                    )
                except Exception as e:
                    status_code = getattr(e, "status_code", None)
                    if status_code is None and hasattr(e, "response"):
                        status_code = getattr(e.response, "status_code", None)

                    key = f"HTTP_{status_code}" if status_code else "exception_no_status"
                    self.stats["errors_by_status"][key] = (
                        self.stats["errors_by_status"].get(key, 0) + 1
                    )
                    console.print(f"[red]Batch exception: {type(e).__name__}: {e}[/red]")
                    total_failed += len(chunk)
                    break

                if isinstance(result, CreateSegmentsBatchResponse201):
                    total_created += result.created
                    total_skipped += result.skipped
                    break

                if self._is_rate_limit_error(result):
                    wait = _RATE_LIMIT_WAIT_SECONDS
                    console.print(
                        f"[yellow]Rate limited on batch {chunk_idx}."
                        f" Waiting {wait}s (attempt {attempt + 1}/{max_retries})...[/yellow]"
                    )
                    if attempt < max_retries - 1:
                        time.sleep(wait)
                        continue
                    console.print(
                        f"[red]Max retries reached for batch {chunk_idx}[/red]"
                    )

                # Non-retryable API error
                if self._is_api_error(result):
                    status_code = self._get_error_attr(result, "status")
                    key = f"HTTP_{status_code}" if status_code else "api_error_no_status"
                    self.stats["errors_by_status"][key] = (
                        self.stats["errors_by_status"].get(key, 0) + 1
                    )
                    console.print(f"[red]Batch {chunk_idx} failed:[/red]")
                    self._print_api_error(result)

                    if self._is_auth_error(result):
                        console.print("[red]Authentication error — aborting.[/red]")
                        total_failed += len(chunk)
                        return total_created, total_skipped, total_failed
                else:
                    key = "unknown_error_none_result" if result is None else (
                        f"unknown_{type(result).__name__}"
                    )
                    self.stats["errors_by_status"][key] = (
                        self.stats["errors_by_status"].get(key, 0) + 1
                    )
                    console.print(
                        f"[red]Batch {chunk_idx}: unexpected result"
                        f" ({type(result).__name__}): {result}[/red]"
                    )

                total_failed += len(chunk)
                break

        return total_created, total_skipped, total_failed

    def upload_media(self, media_folder: Path, episode_filter: int | None = None) -> bool:
        """Upload a single media (all episodes and segments).

        Args:
            media_folder: Path to the media folder
            episode_filter: Optional episode number to filter upload
        """
        media_id_str = media_folder.name

        # Check upload history — skip fully completed media
        if self.history and not self.dry_run and self.history.is_media_complete(media_id_str):
            console.print(f"\n[dim]Skipping {media_id_str} (already completed)[/dim]")
            return True

        console.print(f"\n[bold cyan]Processing: {media_id_str}[/bold cyan]")

        # Load media info
        media_info = self._load_media_info(media_folder)
        if not media_info:
            return False

        # Get or create media
        media_id = self._get_or_create_media(media_info, media_folder)
        if not media_id:
            return False

        storage_base_path = f"media/{media_info.anilist_id}"

        # Skip episodes if update_info_only is True
        if self.update_info_only:
            console.print("[cyan]Info-only mode: Skipping episode/segment processing[/cyan]")
            return True

        nsfw_lookup = self._load_nsfw_lookup(media_folder)
        if nsfw_lookup:
            console.print(f"[dim]Loaded NSFW lookup: {len(nsfw_lookup)} segments[/dim]")
        else:
            console.print("[yellow]No _nsfw_results/results.json found — content_rating must be in _data.json[/yellow]")

        # Process each episode folder
        episode_folders = sorted(
            [d for d in media_folder.iterdir() if d.is_dir() and not d.name.startswith("_")]
        )

        has_errors = False
        all_episodes_ok = True
        for episode_folder in episode_folders:
            try:
                episode_number = int(episode_folder.name)
            except ValueError:
                console.print(
                    f"[yellow]Skipping non-episode folder: {episode_folder.name}[/yellow]"
                )
                continue

            if episode_filter and episode_number != episode_filter:
                continue

            # Check upload history — skip already-uploaded episodes
            if (
                self.history
                and not self.dry_run
                and self.history.is_episode_done(media_id_str, episode_number)
            ):
                console.print(
                    f"\n[dim]Skipping episode {episode_number} (already uploaded)[/dim]"
                )
                continue

            try:
                ep_ok = self.upload_episode(
                    media_id, episode_folder, storage_base_path=storage_base_path,
                    nsfw_lookup=nsfw_lookup,
                )
            except Exception as e:
                console.print(
                    f"[red]Episode {episode_number} failed with error: {e}[/red]"
                )
                ep_ok = False

            if not ep_ok:
                has_errors = True
                all_episodes_ok = False
            elif self.history and not self.dry_run:
                self.history.mark_episode_done(media_id_str, episode_number)

        # Mark media as fully complete if all episodes succeeded and no filter was used
        if self.history and not self.dry_run and all_episodes_ok and not episode_filter:
            self.history.mark_media_complete(media_id_str)

        return not has_errors

    def _upload_segment_files(
        self,
        storage_base_path: str,
        episode_number: int,
        segment: SegmentData,
        episode_folder: Path,
        existing_files: set[str],
    ) -> tuple[str, list[str], list[str]]:
        """Upload R2 files for a single segment. Returns (segment_hash, uploaded, skipped)."""
        uploaded: list[str] = []
        skipped: list[str] = []

        for _file_type, filename in segment.files.items():
            if not filename:
                continue
            filepath = episode_folder / filename
            if not filepath.exists():
                continue

            if filename in existing_files:
                skipped.append(filename)
            else:
                url = self.r2.upload_file(filepath, storage_base_path, episode_number)
                if url:
                    uploaded.append(filename)
                else:
                    uploaded.append(f"{filename} (FAILED)")

        return segment.segment_hash, uploaded, skipped

    def upload_episode(
        self,
        media_id: int,
        episode_folder: Path,
        max_r2_workers: int = 30,
        storage_base_path: str = "",
        nsfw_lookup: dict[str, dict] | None = None,
    ) -> bool:
        """Upload a single episode using two-phase processing.

        Phase 1: Upload all files to R2 with high concurrency.
        Phase 2: Create all segments via batch API.
        """
        # Reset per-episode stats
        self.stats = {
            "total": 0,
            "uploaded": 0,
            "duplicated": 0,
            "skipped_no_hash": 0,
            "skipped_no_translations": 0,
            "skipped_too_long": 0,
            "skipped_constraint": 0,
            "failed": 0,
            "errors_by_status": {},
        }

        console.print(f"\n[cyan]Processing episode: {episode_folder.name}[/cyan]")

        episode_data = self._load_episode_data(episode_folder, nsfw_lookup=nsfw_lookup)
        if not episode_data:
            return False

        if not self._get_or_create_episode(media_id, episode_data):
            return False

        total = len(episode_data.segments)
        episode_number = episode_data.number

        # --- Phase 1: R2 file uploads (high concurrency, no rate limiting) ---
        if self.upload_r2 and self.r2 and not self.dry_run:
            console.print(
                f"[cyan]Phase 1: Uploading files to R2 ({max_r2_workers} workers)...[/cyan]"
            )

            # Batch existence check — one list call replaces hundreds of head_object calls
            existing_files = self.r2.list_existing_files(storage_base_path, episode_number)
            console.print(f"[dim]  Found {len(existing_files)} files already in R2[/dim]")

            # Collect segments that need file uploads
            segments_needing_upload = [
                seg for seg in episode_data.segments
                if not self._should_skip_segment(seg)[0]
                and any(
                    (episode_folder / fn).exists() and fn not in existing_files
                    for fn in seg.files.values()
                    if fn
                )
            ]

            if segments_needing_upload:
                total_r2_uploaded = 0
                total_r2_skipped = 0

                with ThreadPoolExecutor(max_workers=max_r2_workers) as upload_pool:
                    futures = {
                        upload_pool.submit(
                            self._upload_segment_files,
                            storage_base_path,
                            episode_number,
                            segment,
                            episode_folder,
                            existing_files,
                        ): segment
                        for segment in segments_needing_upload
                    }

                    for future in as_completed(futures):
                        try:
                            seg_hash, uploaded, skipped = future.result()
                            total_r2_uploaded += len([f for f in uploaded if "(FAILED)" not in f])
                            total_r2_skipped += len(skipped)
                        except Exception as e:
                            segment = futures[future]
                            self._print(
                                f"[red]  R2 upload error for {segment.segment_hash}: {e}[/red]"
                            )

                console.print(
                    f"[green]  R2 done: {total_r2_uploaded} uploaded, "
                    f"{total_r2_skipped} already existed[/green]"
                )
            else:
                console.print("[dim]  All files already in R2, skipping upload phase[/dim]")
        elif self.upload_r2 and self.dry_run:
            console.print("[cyan]Phase 1: [DRY RUN] Would upload files to R2[/cyan]")

        # --- Phase 2: Batch API segment creation ---
        console.print(f"[cyan]Phase 2: Creating {total} segments via batch API...[/cyan]")

        # Filter and build requests
        api_requests: list[SegmentCreateRequest] = []
        for segment in episode_data.segments:
            self.stats["total"] += 1
            should_skip, skip_reason = self._should_skip_segment(segment)
            if should_skip:
                if skip_reason == "no segment hash":
                    self.stats["skipped_no_hash"] += 1
                elif "translation" in skip_reason:
                    self.stats["skipped_no_translations"] += 1
                elif "content too long" in skip_reason:
                    self.stats["skipped_too_long"] += 1
                continue
            api_requests.append(self._build_segment_request(segment))

        valid_count = len(api_requests)
        skipped_count = total - valid_count
        if skipped_count:
            console.print(f"[dim]  {skipped_count} segments skipped (pre-filter)[/dim]")

        if self.dry_run:
            console.print(
                f"[cyan][DRY RUN] Would create {valid_count} segments"
                f" in batch (from {total} total)[/cyan]"
            )
            for req in api_requests:
                ja_content = getattr(req.text_ja, "content", "?")
                preview = ja_content[:30] + "..." if len(ja_content) > 30 else ja_content
                console.print(f"  [dim]{req.hashed_id} pos={req.position} {preview}[/dim]")
            self.stats["uploaded"] = valid_count
        elif api_requests:
            created, duped, failed = self._create_segments_batch(
                media_id, episode_number, api_requests,
            )
            self.stats["uploaded"] = created
            self.stats["duplicated"] = duped
            self.stats["failed"] = failed

        console.print(
            f"[green]Completed episode {episode_number}:[/green] "
            f"{total} total, "
            f"[green]{self.stats['uploaded']} ok[/green], "
            f"[yellow]{self.stats['duplicated']} duplicated[/yellow], "
            f"[red]{self.stats['failed']} failed[/red]"
        )

        # Print detailed statistics
        s = self.stats
        parts = []
        if s["skipped_no_hash"] > 0:
            parts.append(f"[dim]no hash: {s['skipped_no_hash']}[/dim]")
        if s["skipped_no_translations"] > 0:
            parts.append(f"[dim]no translations: {s['skipped_no_translations']}[/dim]")
        if s["skipped_too_long"] > 0:
            parts.append(f"[dim]too long: {s['skipped_too_long']}[/dim]")
        if s["skipped_constraint"] > 0:
            parts.append(f"[dim]constraint: {s['skipped_constraint']}[/dim]")
        if parts:
            console.print(f"  Skipped: {', '.join(parts)}")

        # Print error breakdown by status code
        if s["errors_by_status"]:
            console.print("  [bold]Error breakdown:[/bold]")
            for error_type, count in sorted(s["errors_by_status"].items()):
                console.print(f"    [red]{error_type}:[/red] {count}")

        return self.stats["failed"] == 0


def scan_output_directory(output_path: Path) -> list[Path]:
    """Scan output directory for media folders."""
    media_folders = []

    for item in output_path.iterdir():
        if item.is_dir() and not item.name.startswith("_") and (item / "_info.json").exists():
            media_folders.append(item)

    return sorted(media_folders, key=lambda x: x.name)


def _format_size(size_bytes: int) -> str:
    """Format bytes to human readable size."""
    for unit in ["B", "KB", "MB", "GB"]:
        if size_bytes < 1024.0:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.1f} TB"


def _collect_upload_info(
    media_folders: list[Path],
    episode_filter: int | None,
    r2_uploader: R2Uploader | None,
    upload_r2: bool = False,
) -> dict:
    """Collect information about what will be uploaded."""
    total_media = len(media_folders)
    total_episodes = 0
    total_segments = 0
    total_files = 0
    total_size = 0

    media_details = []

    for media_folder in media_folders:
        # Load media info
        info_path = media_folder / "_info.json"
        if not info_path.exists():
            continue

        with open(info_path) as f:
            media_data = json.load(f)

        media_id = media_data.get("anilist_id", media_data.get("id"))
        media_title = media_data.get("romaji_name", media_folder.name)

        # Collect episodes
        episode_folders = sorted(
            [d for d in media_folder.iterdir() if d.is_dir() and not d.name.startswith("_")]
        )

        episodes_to_upload = []
        for episode_folder in episode_folders:
            try:
                episode_number = int(episode_folder.name)
            except ValueError:
                continue

            if episode_filter and episode_number != episode_filter:
                continue

            # Load episode data
            data_path = episode_folder / "_data.json"
            if not data_path.exists():
                continue

            with open(data_path) as f:
                episode_data = json.load(f)

            segments = episode_data.get("segments", [])

            # Count files to upload (only if uploading to R2)
            episode_files = 0
            episode_size = 0
            if upload_r2:
                for segment in segments:
                    for _file_type, filename in segment.get("files", {}).items():
                        if not filename:
                            continue
                        filepath = episode_folder / filename
                        if filepath.exists():
                            episode_files += 1
                            episode_size += filepath.stat().st_size

            episodes_to_upload.append(
                {
                    "number": episode_number,
                    "segments": len(segments),
                    "files": episode_files,
                    "size": episode_size,
                }
            )

            total_episodes += 1
            total_segments += len(segments)
            total_files += episode_files
            total_size += episode_size

        if episodes_to_upload:
            media_details.append(
                {
                    "id": media_id,
                    "title": media_title,
                    "episodes": episodes_to_upload,
                }
            )

    return {
        "total_media": total_media,
        "total_episodes": total_episodes,
        "total_segments": total_segments,
        "total_files": total_files,
        "total_size": total_size,
        "media_details": media_details,
    }


def _display_upload_summary(
    info: dict, target: str, storage_target: str, upload_r2: bool = False
) -> None:
    """Display a summary of what will be uploaded."""
    color = "red" if target == "prod" else ("cyan" if target == "dev" else "green")

    console.print(f"\n[bold {color}]{'='*60}[/bold {color}]")
    console.print(f"[bold {color}]UPLOAD SUMMARY[/bold {color}]")
    console.print(f"[bold {color}]{'='*60}[/bold {color}]")

    console.print(f"\n[bold]Media:[/bold] {info['total_media']}")
    console.print(f"[bold]Episodes:[/bold] {info['total_episodes']}")
    console.print(f"[bold]Segments:[/bold] {info['total_segments']}")
    console.print(f"[bold]API target:[/bold] {target}")
    console.print(f"[bold]Storage target:[/bold] {storage_target}")

    if storage_target == "r2" and upload_r2:
        console.print(f"[bold]Files to upload:[/bold] {info['total_files']}")
        console.print(f"[bold]Total size:[/bold] {_format_size(info['total_size'])}")
    elif storage_target == "r2":
        console.print("[dim]R2 upload: [bold]SKIPPED[/bold] (--upload-r2 not specified)[/dim]")
    else:
        console.print("[dim]Files to R2: [bold]N/A[/bold] (storage target is local)[/dim]")

    for media in info["media_details"]:
        console.print(f"\n[cyan]▸ {media['title']} (ID: {media['id']})[/cyan]")
        for ep in media["episodes"]:
            size_str = _format_size(ep["size"])
            console.print(
                f"  [dim]E{ep['number']:02d}[/dim] - {ep['segments']} segments, "
                f"{ep['files']} files, {size_str}"
            )

    console.print(f"\n[bold {color}]{'='*60}[/bold {color}]\n")


def upload_all(
    output_path: str,
    media_id: str | None = None,
    episode: int | None = None,
    env: str = "local",
    storage_target: str = "local",
    dry_run: bool = True,
    upload_r2: bool = False,
    update_info_only: bool = False,
    skip_confirm: bool = False,
) -> None:
    """Upload all media from the output directory.

    Args:
        output_path: Path to media folder (e.g., /path/to/output/12345)
        media_id: Ignored (kept for backwards compatibility). Use output_path directly.
        episode: Optional episode number to filter upload
        env: API environment to upload to (local, dev, or prod). Default is local.
        storage_target: Storage target for files ("local" or "r2").
        dry_run: Show what would be uploaded without actually uploading. Default is True.
        upload_r2: Actually upload files to R2. Only used when storage_target="r2".
        update_info_only: Only update media info (skip episodes and segments)
    """
    media_folder = Path(output_path).resolve()

    if not media_folder.exists():
        console.print(f"[red]Media folder does not exist: {media_folder}[/red]")
        return

    # Verify it's a valid media folder (has _info.json)
    if not (media_folder / "_info.json").exists():
        console.print(
            f"[red]Invalid media folder (missing _info.json): {media_folder}[/red]"
        )
        return

    if env not in ("local", "dev", "prod"):
        console.print(f"[red]Invalid environment: {env}. Must be 'local', 'dev', or 'prod'[/red]")
        return

    if storage_target not in ("local", "r2"):
        console.print(
            f"[red]Invalid storage target: {storage_target}. Must be 'local' or 'r2'[/red]"
        )
        return

    if storage_target == "local" and upload_r2:
        console.print(
            "[red]Invalid combination: --upload-r2 requires --storage r2.[/red]"
        )
        return

    # Load config
    config = Config.from_env(env=env)
    if not config.validate(storage_target=storage_target, upload_r2=upload_r2):
        return

    # Display target
    config.display_target()

    # Check if episode filter exists
    if episode:
        episode_folder = media_folder / str(episode)
        if not episode_folder.exists() or not (episode_folder / "_data.json").exists():
            console.print(f"[yellow]No episode {episode} found in media folder[/yellow]")
            return

    # Collect and display upload info
    # Only initialize R2Uploader when we'll actually use it
    r2 = R2Uploader(config) if upload_r2 else None
    upload_info = _collect_upload_info([media_folder], episode, r2, upload_r2)

    if upload_info["total_files"] == 0 and not dry_run and storage_target == "r2" and upload_r2:
        console.print("[yellow]All files already uploaded. Nothing to do.[/yellow]")
        return

    _display_upload_summary(upload_info, config.target, storage_target, upload_r2)

    # Safety check for prod
    if config.is_prod and not dry_run and not skip_confirm:
        console.print(
            "[bold red] Type 'yes' to confirm upload to PRODUCTION: [/bold red]", end=""
        )
        if input() != "yes":
            console.print("[yellow]Upload cancelled.[/yellow]")
            return

    # Initialize upload history (persisted per-env alongside media folders)
    history = None
    if not dry_run:
        history = UploadHistory(media_folder.parent, env)

    uploader = NadeshikoUploader(
        config,
        dry_run=dry_run,
        storage_target=storage_target,
        upload_r2=upload_r2,
        update_info_only=update_info_only,
        history=history,
    )

    # Upload the media
    success = uploader.upload_media(media_folder, episode_filter=episode)
    if success:
        console.print("\n[green]Upload complete![/green]")
    else:
        console.print("\n[yellow]Upload completed with errors (will retry next run).[/yellow]")
