"""Nadeshiko segment uploader.

Uploads media segments generated by media-sub-splitter to:
- Nadeshiko API (metadata)
- Cloudflare R2 (media files, optional - use --upload-r2 flag)

By default, only the backend is updated without uploading files to R2.
"""

import json
import os
import threading
import time
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from datetime import timedelta
from pathlib import Path

import boto3
from botocore.exceptions import ClientError
from dotenv import load_dotenv
from rich.console import Console
from rich.progress import BarColumn, Progress, TaskID, TextColumn, TimeRemainingColumn

load_dotenv(override=True)

console = Console()

# Nadeshiko SDK imports
from nadeshiko import Nadeshiko
from nadeshiko.api.media import media_index, episode_show
from nadeshiko.models.error import Error as PublicError
from nadeshiko_internal.api.media import (
    media_create,
    media_update,
    episode_create,
    episode_update,
    segment_create,
)
from nadeshiko_internal.models.error import Error as InternalError
from nadeshiko_internal.models.character_input import CharacterInput
from nadeshiko_internal.models.character_input_character_role import CharacterInputCharacterRole
from nadeshiko_internal.models.media_create_request import MediaCreateRequest
from nadeshiko_internal.models.media_create_request_category import MediaCreateRequestCategory
from nadeshiko_internal.models.media_create_request_storage import MediaCreateRequestStorage
from nadeshiko_internal.models.media_update_request import MediaUpdateRequest
from nadeshiko_internal.models.media_update_request_storage import MediaUpdateRequestStorage
from nadeshiko_internal.models.episode_create_request import EpisodeCreateRequest
from nadeshiko_internal.models.segment_create_request import SegmentCreateRequest
from nadeshiko_internal.models.segment_create_request_storage import SegmentCreateRequestStorage
from nadeshiko_internal.types import UNSET

# R2 S3-compatible endpoint
# R2 S3-compatible endpoint
R2_ENDPOINT_TEMPLATE = "https://{account_id}.r2.cloudflarestorage.com"

# Pattern to detect raw R2 URLs that need to be replaced with CDN URLs
RAW_R2_PATTERN = "https://{account_id}.r2.cloudflarestorage.com"


def normalize_r2_url(url: str, r2_public_url: str) -> str:
    """Convert raw R2 URL to CDN URL if needed.

    Args:
        url: The URL to normalize (may be raw R2 or already CDN)
        r2_public_url: The CDN base URL (e.g., https://cdn.nadeshiko.co)

    Returns:
        The normalized URL using the CDN domain
    """
    if not url:
        return url

    # If URL is already using the CDN domain, return as-is
    if url.startswith(r2_public_url):
        return url

    # If URL is a raw R2 URL, extract the path and prepend CDN domain
    if ".r2.cloudflarestorage.com/" in url:
        # Extract path after the bucket/domain
        parts = url.split("/media/", 1)
        if len(parts) == 2:
            return f"{r2_public_url}/media/{parts[1]}"

    return url


@dataclass
class Config:
    """Configuration from environment variables."""

    nadeshiko_api_key: str
    nadeshiko_base_url: str
    r2_account_id: str
    r2_access_key_id: str
    r2_secret_access_key: str
    r2_bucket: str
    r2_public_url: str
    target: str = "local"
    is_prod: bool = False

    @classmethod
    def from_env(cls, env: str = "local") -> "Config":
        if env not in ("local", "dev", "prod"):
            raise ValueError(f"Invalid environment: {env}")

        def _first_set(*names: str, default: str = "") -> str:
            for name in names:
                value = os.getenv(name)
                if value:
                    return value
            return default

        if env == "local":
            return cls(
                nadeshiko_api_key=_first_set("NADESHIKO_LOCAL_API_KEY", "NADESHIKO_API_KEY"),
                nadeshiko_base_url=_first_set(
                    "NADESHIKO_LOCAL_BASE_URL",
                    "NADESHIKO_BASE_URL",
                    default="http://localhost:5000",
                ),
                r2_account_id=os.getenv("R2_ACCOUNT_ID", ""),
                r2_access_key_id=os.getenv("R2_ACCESS_KEY_ID", ""),
                r2_secret_access_key=os.getenv("R2_SECRET_ACCESS_KEY", ""),
                r2_bucket=os.getenv("R2_BUCKET", "nadeshiko-segments"),
                r2_public_url=os.getenv("R2_PUBLIC_URL", ""),
                target="local",
                is_prod=False,
            )

        if env == "dev":
            return cls(
                nadeshiko_api_key=_first_set("NADESHIKO_DEV_API_KEY", "NADESHIKO_API_KEY"),
                nadeshiko_base_url=_first_set(
                    "NADESHIKO_DEV_BASE_URL",
                    default="https://api-dev.nadeshiko.co",
                ),
                r2_account_id=os.getenv("R2_ACCOUNT_ID", ""),
                r2_access_key_id=os.getenv("R2_ACCESS_KEY_ID", ""),
                r2_secret_access_key=os.getenv("R2_SECRET_ACCESS_KEY", ""),
                r2_bucket=os.getenv("R2_BUCKET", "nadeshiko-segments"),
                r2_public_url=os.getenv("R2_PUBLIC_URL", ""),
                target="dev",
                is_prod=False,
            )

        return cls(
            nadeshiko_api_key=os.getenv("NADESHIKO_PROD_API_KEY", ""),
            nadeshiko_base_url=os.getenv("NADESHIKO_PROD_BASE_URL", "https://api.nadeshiko.co"),
            r2_account_id=os.getenv("R2_ACCOUNT_ID", ""),
            r2_access_key_id=os.getenv("R2_ACCESS_KEY_ID", ""),
            r2_secret_access_key=os.getenv("R2_SECRET_ACCESS_KEY", ""),
            r2_bucket=os.getenv("R2_BUCKET", "nadeshiko-segments"),
            r2_public_url=os.getenv("R2_PUBLIC_URL", ""),
            target="prod",
            is_prod=True,
        )

    def validate(self, storage_target: str = "local", upload_r2: bool = False) -> bool:
        """Check that required config is present.

        Args:
            storage_target: Where media files should be served from ("local" or "r2").
            upload_r2: Whether files will be uploaded to R2. If False, R2 credentials are optional.
        """
        missing = []
        if not self.nadeshiko_api_key:
            if self.target == "local":
                missing.append("NADESHIKO_LOCAL_API_KEY (or NADESHIKO_API_KEY)")
            elif self.target == "dev":
                missing.append("NADESHIKO_DEV_API_KEY (or NADESHIKO_API_KEY)")
            else:
                missing.append("NADESHIKO_PROD_API_KEY")

        # R2 credentials are required only when files are uploaded to R2.
        needs_r2 = upload_r2

        if needs_r2:
            if not self.r2_public_url:
                missing.append("R2_PUBLIC_URL")
            if not self.r2_account_id:
                missing.append("R2_ACCOUNT_ID")
            if not self.r2_access_key_id:
                missing.append("R2_ACCESS_KEY_ID")
            if not self.r2_secret_access_key:
                missing.append("R2_SECRET_ACCESS_KEY")
            if not self.r2_bucket:
                missing.append("R2_BUCKET")

        if missing:
            console.print(f"[red]Missing required env vars: {', '.join(missing)}[/red]")
            return False
        return True

    def display_target(self) -> None:
        """Display the upload target with appropriate styling."""
        if self.is_prod:
            console.print(
                "\n[bold red on white] TARGET: PRODUCTION [/bold red on white]\n"
                "[bold red] This will upload to PRODUCTION! [/bold red]"
            )
        elif self.target == "dev":
            console.print(
                "\n[bold cyan] TARGET: DEV [/bold cyan]\n"
                f"[dim] API: {self.nadeshiko_base_url}[/dim]"
            )
        else:
            console.print(
                "\n[bold green] TARGET: LOCAL [/bold green]\n"
                f"[dim] API: {self.nadeshiko_base_url}[/dim]"
            )


@dataclass
class SegmentData:
    """Segment data from _data.json."""

    segment_hash: str
    segment_index: int
    start_ms: int
    end_ms: int
    duration_ms: int
    content_ja: str
    content_es: str | None
    content_en: str | None
    is_mt_es: bool
    is_mt_en: bool
    actor_ja: str | None
    actor_es: str | None
    actor_en: str | None
    files: dict[str, str]  # audio, screenshot, preview, video filenames
    subtitles: dict  # ja, es, en subtitle details


@dataclass
class EpisodeData:
    """Episode data from _data.json."""

    number: int
    duration_ms: int
    total_segments: int
    segments: list[SegmentData]
    ignored_segments: list[dict]


@dataclass
class MediaInfo:
    """Media info from _info.json."""

    anilist_id: int
    japanese_name: str | None
    english_name: str | None
    romaji_name: str
    airing_format: str
    airing_status: str
    genres: list[str]
    version: str
    hash_salt: str
    cover_url: str | None
    banner_url: str | None
    start_date: str | None  # ISO format date string (YYYY-MM-DD)
    end_date: str | None  # ISO format date string (YYYY-MM-DD)
    characters: list[dict] | None = None
    studio: str | None = None
    season_name: str | None = None
    season_year: int | None = None


class R2Uploader:
    """Handles file uploads to Cloudflare R2."""

    def __init__(self, config: Config):
        self.config = config
        self.endpoint = R2_ENDPOINT_TEMPLATE.format(account_id=config.r2_account_id)
        self.bucket = config.r2_bucket
        self.public_url = config.r2_public_url

        self.s3_client = boto3.client(
            "s3",
            endpoint_url=self.endpoint,
            aws_access_key_id=config.r2_access_key_id,
            aws_secret_access_key=config.r2_secret_access_key,
        )

    def get_r2_key(self, media_id: int, episode_number: int, filename: str) -> str:
        """Generate R2 object key for a file."""
        return f"media/{media_id}/{episode_number}/{filename}"

    def upload_file(
        self, filepath: Path, media_id: int, episode_number: int, progress: Progress | None = None, task_id: TaskID | None = None
    ) -> str | None:
        """Upload a file to R2 and return its public URL."""
        key = self.get_r2_key(media_id, episode_number, filepath.name)

        try:
            callback = None
            if progress and task_id:
                callback = lambda bytes_transferred: progress.update(task_id, advance=bytes_transferred)

            self.s3_client.upload_file(
                str(filepath),
                self.bucket,
                key,
                Callback=callback,
            )
            # Return public URL
            return f"{self.public_url}/{key}"
        except ClientError as e:
            console.print(f"[red]Error uploading {filepath.name}: {e}[/red]")
            return None

    def file_exists(self, media_id: int, episode_number: int, filename: str) -> bool:
        """Check if a file already exists in R2."""
        key = self.get_r2_key(media_id, episode_number, filename)
        try:
            self.s3_client.head_object(Bucket=self.bucket, Key=key)
            return True
        except ClientError:
            return False

    def get_media_r2_key(self, media_id: int, filename: str) -> str:
        """Generate R2 object key for a media-level file (cover/banner)."""
        return f"media/{media_id}/{filename}"

    def upload_media_file(self, filepath: Path, media_id: int) -> str | None:
        """Upload a media-level file (cover/banner) to R2 and return its public URL."""
        key = self.get_media_r2_key(media_id, filepath.name)

        try:
            self.s3_client.upload_file(str(filepath), self.bucket, key)
            return f"{self.public_url}/{key}"
        except ClientError as e:
            console.print(f"[red]Error uploading {filepath.name}: {e}[/red]")
            return None

    def media_file_exists(self, media_id: int, filename: str) -> bool:
        """Check if a media-level file already exists in R2."""
        key = self.get_media_r2_key(media_id, filename)
        try:
            self.s3_client.head_object(Bucket=self.bucket, Key=key)
            return True
        except ClientError:
            return False

    def get_media_file_url(self, media_id: int, filename: str) -> str:
        """Get the public URL for a media-level file."""
        key = self.get_media_r2_key(media_id, filename)
        return f"{self.public_url}/{key}"


# Global rate limit state shared across all uploader instances
_rate_limit_lock = threading.Lock()
_rate_limit_until = 0.0
_RATE_LIMIT_WAIT_SECONDS = 60  # Fixed 1 minute wait for rate limits
# Semaphore to limit concurrent API requests and prevent exhausting rate limit
_request_semaphore = threading.Semaphore(5)  # Max 5 concurrent requests
# Minimum delay between requests to stay under rate limit (300 per 60s = 5 per sec)
# 5 req/s = 1 request every 200ms globally
_MIN_REQUEST_DELAY = 0.2  # 200ms between requests globally
_last_request_time = 0.0
_last_request_lock = threading.Lock()

def _wait_for_rate_limit() -> None:
    """Wait if globally rate limited. Called by all threads before API requests."""
    global _rate_limit_until
    while True:
        with _rate_limit_lock:
            wait_until = _rate_limit_until
            if wait_until <= time.time():
                # Clear the rate limit if time has passed
                _rate_limit_until = 0.0
                break
        # Wait outside the lock to allow other threads to check
        sleep_time = max(0, wait_until - time.time())
        if sleep_time > 0:
            time.sleep(min(sleep_time, 1.0))  # Sleep in small increments to check state

def _set_rate_limit() -> None:
    """Set global rate limit. All threads will wait for 60 seconds."""
    global _rate_limit_until
    with _rate_limit_lock:
        _rate_limit_until = time.time() + _RATE_LIMIT_WAIT_SECONDS

def _wait_for_request_delay() -> None:
    """Wait to ensure minimum delay between requests."""
    global _last_request_time
    with _last_request_lock:
        now = time.time()
        time_since_last = now - _last_request_time
        if time_since_last < _MIN_REQUEST_DELAY:
            time.sleep(_MIN_REQUEST_DELAY - time_since_last)
        _last_request_time = time.time()


class NadeshikoUploader:
    """Handles uploading to Nadeshiko API and R2."""

    # Maximum content length for segments (characters)
    MAX_CONTENT_LENGTH = 500

    def __init__(
        self,
        config: Config,
        dry_run: bool = False,
        storage_target: str = "local",
        upload_r2: bool = False,
        update_info_only: bool = False,
    ):
        self.config = config
        self.dry_run = dry_run
        self.storage_target = storage_target
        self.upload_r2 = upload_r2
        self.update_info_only = update_info_only
        # Only initialize R2Uploader when we'll actually use it
        self.r2 = R2Uploader(config) if upload_r2 else None

        self.api_client = Nadeshiko(
            token=config.nadeshiko_api_key,
            base_url=config.nadeshiko_base_url,
        )
        self.media_index = media_index
        self.media_create = media_create
        self.media_update = media_update
        self.episode_show = episode_show
        self.episode_create = episode_create
        self.episode_update = episode_update
        self.segment_create = segment_create
        self.ErrorTypes = (PublicError, InternalError)
        self._console_lock = threading.Lock()
        # Statistics
        self._stats_lock = threading.Lock()
        self.stats = {
            "total": 0,
            "uploaded": 0,
            "skipped_no_hash": 0,
            "skipped_no_translations": 0,
            "skipped_too_long": 0,
            "failed": 0,
        }

        if dry_run:
            console.print("[cyan]Running in DRY-RUN mode. Use --apply to perform actual uploads.[/cyan]")

    def _ms_to_hmsff(self, milliseconds: int) -> str:
        """Convert milliseconds to H:MM:SS.ffffff format."""
        td = timedelta(milliseconds=milliseconds)
        total_seconds = td.total_seconds()
        hours = int(total_seconds // 3600)
        minutes = int((total_seconds % 3600) // 60)
        seconds = total_seconds % 60
        return f"{hours}:{minutes:02d}:{seconds:06f}"

    def _get_error_attr(self, error: object, attr_name: str):
        """Safely read SDK error attributes that may raise KeyError."""
        try:
            return getattr(error, attr_name)
        except (KeyError, AttributeError):
            return None

    def _is_api_error(self, value: object) -> bool:
        """Check whether a response is an SDK error (public or internal)."""
        return isinstance(value, self.ErrorTypes)

    def _is_auth_error(self, error: object) -> bool:
        """Check for authentication errors returned by the API."""
        status = self._get_error_attr(error, "status")
        code = self._get_error_attr(error, "code")
        return status == 401 or code in {"AUTH_CREDENTIALS_INVALID", "INVALID_API_KEY"}

    def _print_api_error(self, error: object) -> None:
        """Print standard API error details."""
        for attr_name in ["detail", "status", "code", "title", "errors"]:
            value = self._get_error_attr(error, attr_name)
            if value:
                self._print(f"  [red]{attr_name.capitalize()}:[/red] {value}")

    def _is_rate_limit_error(self, error: object) -> bool:
        """Check if an error is a 429 rate limit error."""
        return self._get_error_attr(error, "status") == 429

    def _get_retry_after_seconds(self, error: object) -> int:
        """Get the retry-after seconds from a rate limit error.

        We use a fixed 60-second wait for all rate limit errors to keep
        things simple and reliable.
        """
        return _RATE_LIMIT_WAIT_SECONDS

    def _should_skip_segment(self, segment: SegmentData) -> tuple[bool, str]:
        """Check if a segment should be skipped and return (skip, reason)."""
        # Check if segment has a valid hash
        if not segment.segment_hash:
            return True, "no segment hash"

        # Check if segment has all three translations
        if not segment.content_es:
            return True, "no Spanish translation"
        if not segment.content_en:
            return True, "no English translation"

        # Check if segment is too long
        if len(segment.content_ja) > self.MAX_CONTENT_LENGTH:
            return True, f"content too long ({len(segment.content_ja)} > {self.MAX_CONTENT_LENGTH})"

        return False, ""

    def _coerce_int(self, value: object) -> int | None:
        """Coerce values from _info.json into an integer ID."""
        if isinstance(value, bool):
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, str):
            stripped = value.strip()
            if stripped and stripped.isdigit():
                return int(stripped)
        return None

    def _parse_character_role(self, value: object) -> CharacterInputCharacterRole:
        """Parse AniList role values from _info.json into SDK enum values."""
        if isinstance(value, CharacterInputCharacterRole):
            return value
        role_text = str(value or "").upper()
        for role in CharacterInputCharacterRole:
            if role.value in role_text:
                return role
        return CharacterInputCharacterRole.SUPPORTING

    def _build_character_inputs(self, media_info: MediaInfo) -> list[CharacterInput] | None:
        """Build SDK CharacterInput objects from _info.json character records.

        Returns None when characters were absent in _info.json so we don't
        accidentally overwrite server-side character data.
        """
        raw_characters = media_info.characters
        if raw_characters is None:
            return None
        if not raw_characters:
            return []

        character_inputs: list[CharacterInput] = []
        seen_pairs: set[tuple[int, int]] = set()

        for idx, character in enumerate(raw_characters, start=1):
            if not isinstance(character, dict):
                self._print(f"[yellow]Skipping character #{idx}: invalid shape in _info.json[/yellow]")
                continue

            character_id = self._coerce_int(
                character.get("characterId", character.get("character_id"))
            )
            seiyuu_id = self._coerce_int(character.get("seiyuuId", character.get("seiyuu_id")))

            if character_id is None:
                self._print(f"[yellow]Skipping character #{idx}: missing characterId[/yellow]")
                continue
            if seiyuu_id is None:
                self._print(
                    f"[yellow]Skipping character #{idx} ({character_id}): missing seiyuuId[/yellow]"
                )
                continue

            pair = (character_id, seiyuu_id)
            if pair in seen_pairs:
                continue
            seen_pairs.add(pair)

            character_name_japanese = (
                character.get("characterNameJapanese")
                or character.get("character_name_japanese")
                or character.get("characterNameEnglish")
                or character.get("character_name_english")
                or f"Character {character_id}"
            )
            character_name_english = (
                character.get("characterNameEnglish")
                or character.get("character_name_english")
                or character_name_japanese
            )
            character_image_url = (
                character.get("characterImageUrl")
                or character.get("character_image_url")
                or ""
            )

            seiyuu_name_japanese = (
                character.get("seiyuuNameJapanese")
                or character.get("seiyuu_name_japanese")
                or character.get("seiyuuNameEnglish")
                or character.get("seiyuu_name_english")
                or f"Seiyuu {seiyuu_id}"
            )
            seiyuu_name_english = (
                character.get("seiyuuNameEnglish")
                or character.get("seiyuu_name_english")
                or seiyuu_name_japanese
            )
            seiyuu_image_url = (
                character.get("seiyuuImageUrl") or character.get("seiyuu_image_url") or ""
            )

            character_inputs.append(
                CharacterInput(
                    character_id=character_id,
                    character_name_japanese=str(character_name_japanese),
                    character_name_english=str(character_name_english),
                    character_image_url=str(character_image_url),
                    character_role=self._parse_character_role(
                        character.get("characterRole", character.get("character_role"))
                    ),
                    seiyuu_id=seiyuu_id,
                    seiyuu_name_japanese=str(seiyuu_name_japanese),
                    seiyuu_name_english=str(seiyuu_name_english),
                    seiyuu_image_url=str(seiyuu_image_url),
                )
            )

        if not character_inputs and raw_characters:
            self._print(
                "[yellow]No valid characters found in _info.json; skipping character update[/yellow]"
            )
            return None

        return character_inputs

    def _print(self, *args, **kwargs) -> None:
        """Thread-safe console print."""
        with self._console_lock:
            console.print(*args, **kwargs)

    def _update_media_info(self, existing_media, media_info: MediaInfo, media_folder: Path) -> int | None:
        """Update existing media with storage backend and other info."""
        if self.dry_run:
            console.print(f"[cyan][DRY RUN] Would update media: {existing_media.id}[/cyan]")
            return existing_media.id

        console.print(f"[cyan]Updating media info: {existing_media.id}[/cyan]")

        # Determine storage backend
        storage = (
            MediaUpdateRequestStorage.R2
            if self.storage_target == "r2"
            else MediaUpdateRequestStorage.LOCAL
        )

        # Check for cover/banner files and upload if needed
        for ext in [".jpg", ".jpeg", ".png", ".webp"]:
            cover_path = media_folder / f"cover{ext}"
            if cover_path.exists():
                if self.upload_r2:
                    if not self.r2.media_file_exists(existing_media.id, cover_path.name):
                        self.r2.upload_media_file(cover_path, existing_media.id)
                        console.print(f"[green]Uploaded cover: {cover_path.name}[/green]")
                    else:
                        console.print(f"[dim]Cover already uploaded: {cover_path.name}[/dim]")
                break

        for ext in [".jpg", ".jpeg", ".png", ".webp"]:
            banner_path = media_folder / f"banner{ext}"
            if banner_path.exists():
                if self.upload_r2:
                    if not self.r2.media_file_exists(existing_media.id, banner_path.name):
                        self.r2.upload_media_file(banner_path, existing_media.id)
                        console.print(f"[green]Uploaded banner: {banner_path.name}[/green]")
                    else:
                        console.print(f"[dim]Banner already uploaded: {banner_path.name}[/dim]")
                break

        # Parse dates if available
        import datetime as dt

        start_date = UNSET
        if media_info.start_date:
            try:
                parsed_date = dt.datetime.fromisoformat(media_info.start_date)
                if parsed_date.tzinfo is None:
                    parsed_date = parsed_date.replace(tzinfo=dt.timezone.utc)
                start_date = parsed_date
            except (ValueError, TypeError):
                pass

        end_date = UNSET
        if media_info.end_date:
            try:
                parsed_date = dt.datetime.fromisoformat(media_info.end_date)
                if parsed_date.tzinfo is None:
                    parsed_date = parsed_date.replace(tzinfo=dt.timezone.utc)
                end_date = parsed_date
            except (ValueError, TypeError):
                pass

        # Build update request with only fields that are set
        request = MediaUpdateRequest()
        request.storage = storage
        if start_date is not UNSET:
            request.start_date = start_date
        if end_date is not UNSET:
            request.end_date = end_date
        if media_info.studio:
            request.studio = media_info.studio
        if media_info.season_name:
            request.season_name = media_info.season_name
        if media_info.season_year is not None:
            request.season_year = media_info.season_year
        if media_info.hash_salt:
            request.hash_salt = media_info.hash_salt
        if media_info.version:
            request.version = media_info.version
        character_inputs = self._build_character_inputs(media_info)
        if character_inputs is not None:
            request.characters = character_inputs

        update_result = self.media_update.sync(
            client=self.api_client, id=existing_media.id, body=request
        )

        if update_result and not self._is_api_error(update_result):
            console.print(f"[green]Updated media: {existing_media.id}[/green]")
            return existing_media.id

        if self._is_api_error(update_result):
            console.print("\n[red]Failed to update media:[/red]")
            self._print_api_error(update_result)
        else:
            console.print("[red]Failed to update media: Unknown error[/red]")
        return existing_media.id  # Return ID anyway if update failed

    def _load_media_info(self, media_folder: Path) -> MediaInfo | None:
        """Load _info.json from a media folder."""
        info_path = media_folder / "_info.json"
        if not info_path.exists():
            console.print(f"[yellow]No _info.json found in {media_folder}[/yellow]")
            return None

        with open(info_path) as f:
            data = json.load(f)

        return MediaInfo(
            anilist_id=data.get("anilist_id", data.get("id")),
            japanese_name=data.get("japanese_name"),
            english_name=data.get("english_name"),
            romaji_name=data.get("romaji_name"),
            airing_format=data.get("airing_format", "TV"),
            airing_status=data.get("airing_status", "FINISHED"),
            genres=data.get("genres", []),
            version=data.get("version", "1.0"),
            hash_salt=data.get("hash_salt", ""),
            cover_url=data.get("cover_url"),
            banner_url=data.get("banner_url"),
            start_date=data.get("start_date"),
            end_date=data.get("end_date"),
            characters=data.get("characters"),
            studio=data.get("studio"),
            season_name=data.get("season", {}).get("name"),
            season_year=data.get("season", {}).get("year"),
        )

    def _load_episode_data(self, episode_folder: Path) -> EpisodeData | None:
        """Load _data.json from an episode folder."""
        data_path = episode_folder / "_data.json"
        if not data_path.exists():
            console.print(f"[yellow]No _data.json found in {episode_folder}[/yellow]")
            return None

        with open(data_path) as f:
            data = json.load(f)

        metadata = data.get("metadata", {})
        segments = [
            SegmentData(
                segment_hash=s.get("segment_hash", ""),
                segment_index=s.get("segment_index", 0),
                start_ms=s.get("start_ms", 0),
                end_ms=s.get("end_ms", 0),
                duration_ms=s.get("duration_ms", 0),
                content_ja=s.get("content_ja", ""),
                content_es=s.get("content_es"),
                content_en=s.get("content_en"),
                is_mt_es=s.get("is_mt_es", False),
                is_mt_en=s.get("is_mt_en", False),
                actor_ja=s.get("actor_ja"),
                actor_es=s.get("actor_es"),
                actor_en=s.get("actor_en"),
                files=s.get("files", {}),
                subtitles=s.get("subtitles", {}),
            )
            for s in data.get("segments", [])
        ]

        return EpisodeData(
            number=metadata.get("number", 0),
            duration_ms=metadata.get("duration_ms", 0),
            total_segments=metadata.get("total_segments", 0),
            segments=segments,
            ignored_segments=data.get("ignored_segments", []),
        )

    def _get_or_create_media(self, media_info: MediaInfo, media_folder: Path) -> int | None:
        """Get existing media or create new one. Returns media ID."""
        if self.dry_run or not self.api_client:
            console.print(f"[cyan][DRY RUN] Would get/create media: {media_info.romaji_name}[/cyan]")
            return media_info.anilist_id

        # Try to find existing media by anilist_id - use search endpoint
        try:
            result = self.media_index.sync(client=self.api_client)
        except Exception as e:
            console.print(f"[red]Failed to list media: {type(e).__name__}: {e}[/red]")
            return None

        if self._is_api_error(result):
            if self._is_auth_error(result):
                console.print(
                    "[red]Authentication failed while listing media. "
                    "Check your API key for the selected target (local/dev/prod).[/red]"
                )
            else:
                console.print("\n[red]Failed to list media:[/red]")
                self._print_api_error(result)
            return None

        existing_media = None
        if result and not self._is_api_error(result):
            # Search through results for matching anilist_id
            for media in result.data:
                if media.anilist_id == media_info.anilist_id:
                    console.print(f"[green]Found existing media: {media.id}[/green]")
                    existing_media = media
                    break

        # If media exists, always sync media info (including characters).
        # `--update-info` only controls whether episodes/segments are skipped later.
        if existing_media:
            media_id = self._update_media_info(existing_media, media_info, media_folder)
            return media_id if media_id is not None else existing_media.id

        # Determine storage backend
        storage = (
            MediaCreateRequestStorage.R2
            if self.storage_target == "r2"
            else MediaCreateRequestStorage.LOCAL
        )

        # Upload cover/banner to R2 if they exist locally
        for ext in [".jpg", ".jpeg", ".png", ".webp"]:
            cover_path = media_folder / f"cover{ext}"
            if cover_path.exists():
                if self.upload_r2:
                    if not self.r2.media_file_exists(media_info.anilist_id, cover_path.name):
                        self.r2.upload_media_file(cover_path, media_info.anilist_id)
                        console.print(f"[green]Uploaded cover: {cover_path.name}[/green]")
                    else:
                        console.print(f"[dim]Cover already uploaded: {cover_path.name}[/dim]")
                break

        for ext in [".jpg", ".jpeg", ".png", ".webp"]:
            banner_path = media_folder / f"banner{ext}"
            if banner_path.exists():
                if self.upload_r2:
                    if not self.r2.media_file_exists(media_info.anilist_id, banner_path.name):
                        self.r2.upload_media_file(banner_path, media_info.anilist_id)
                        console.print(f"[green]Uploaded banner: {banner_path.name}[/green]")
                    else:
                        console.print(f"[dim]Banner already uploaded: {banner_path.name}[/dim]")
                break

        # Validate that we have a cover file
        has_cover = any((media_folder / f"cover{ext}").exists() for ext in [".jpg", ".jpeg", ".png", ".webp"])
        if not has_cover:
            console.print("[red]Error: cover image is required but not found. Add cover.jpg/png/webp to the media folder[/red]")
            return None

        # Parse start_date if available, otherwise use epoch
        import datetime as dt

        start_date = UNSET
        if media_info.start_date:
            try:
                parsed_date = dt.datetime.fromisoformat(media_info.start_date)
                # Add UTC timezone if naive
                if parsed_date.tzinfo is None:
                    parsed_date = parsed_date.replace(tzinfo=dt.timezone.utc)
                start_date = parsed_date
            except (ValueError, TypeError):
                console.print(f"[yellow]Warning: Could not parse start_date: {media_info.start_date}[/yellow]")

        # Use epoch as fallback if no start_date
        if start_date is UNSET:
            start_date = dt.datetime(1970, 1, 1, tzinfo=dt.timezone.utc)

        # Parse end_date if available
        end_date = UNSET
        if media_info.end_date:
            try:
                parsed_date = dt.datetime.fromisoformat(media_info.end_date)
                # Add UTC timezone if naive
                if parsed_date.tzinfo is None:
                    parsed_date = parsed_date.replace(tzinfo=dt.timezone.utc)
                end_date = parsed_date
            except (ValueError, TypeError):
                console.print(f"[yellow]Warning: Could not parse end_date: {media_info.end_date}[/yellow]")

        # Validate required fields
        if not media_info.studio:
            console.print("[red]Error: studio is required but not found in _info.json[/red]")
            return None
        if not media_info.season_name:
            console.print("[red]Error: season.name is required but not found in _info.json[/red]")
            return None
        if media_info.season_year is None:
            console.print("[red]Error: season.year is required but not found in _info.json[/red]")
            return None

        character_inputs = self._build_character_inputs(media_info)

        # Create new media
        request = MediaCreateRequest(
            anilist_id=media_info.anilist_id,
            japanese_name=media_info.japanese_name or media_info.romaji_name,
            romaji_name=media_info.romaji_name,
            english_name=media_info.english_name or media_info.romaji_name,
            airing_format=media_info.airing_format,
            airing_status=media_info.airing_status,
            genres=media_info.genres,
            category=MediaCreateRequestCategory.ANIME,
            version=media_info.version,
            studio=media_info.studio,
            season_name=media_info.season_name,
            season_year=media_info.season_year,
            hash_salt=media_info.hash_salt,
            storage=storage,
            start_date=start_date,
            end_date=end_date,
            characters=character_inputs if character_inputs is not None else UNSET,
        )

        create_result = self.media_create.sync(client=self.api_client, body=request)

        if create_result and not self._is_api_error(create_result):
            console.print(f"[green]Created new media: {create_result.id}[/green]")
            return create_result.id

        if self._is_api_error(create_result):
            console.print("\n[red]Failed to create media:[/red]")
            self._print_api_error(create_result)
        else:
            console.print("[red]Failed to create media: Unknown error[/red]")
            console.print(f"[dim]Result type: {type(create_result)}[/dim]")
            console.print(f"[dim]Result: {create_result}[/dim]")
        return None

    def _get_or_create_episode(self, media_id: int, episode_data: EpisodeData) -> bool:
        """Get existing episode or create new one."""
        if self.dry_run or not self.api_client:
            console.print(f"[cyan][DRY RUN] Would get/create episode: E{episode_data.number}[/cyan]")
            return True

        # Try to find existing episode
        try:
            result = self.episode_show.sync(
                client=self.api_client, media_id=media_id, episode_number=episode_data.number
            )
        except Exception as e:
            console.print(f"[red]Failed to check episode E{episode_data.number}: {type(e).__name__}: {e}[/red]")
            return False

        if result and not self._is_api_error(result):
            console.print(f"[green]Found existing episode: E{episode_data.number}[/green]")
            return True

        if self._is_api_error(result):
            status = self._get_error_attr(result, "status")
            if self._is_auth_error(result):
                console.print(
                    "[red]Authentication failed while checking episodes. "
                    "Check your API key for the selected target (local/dev/prod).[/red]"
                )
                return False
            if status != 404:
                console.print(f"\n[red]Failed to check episode E{episode_data.number}:[/red]")
                self._print_api_error(result)
                return False

        # Create new episode
        request = EpisodeCreateRequest(episode_number=episode_data.number)
        create_result = self.episode_create.sync(
            client=self.api_client, media_id=media_id, body=request
        )

        if create_result and not self._is_api_error(create_result):
            console.print(f"[green]Created new episode: E{episode_data.number}[/green]")
            return True

        if self._is_api_error(create_result):
            console.print("\n[red]Failed to create episode:[/red]")
            console.print(f"  [red]Episode:[/red] {episode_data.number}")
            self._print_api_error(create_result)
        else:
            console.print("[red]Failed to create episode: Unknown error[/red]")
            console.print(f"[dim]Result type: {type(create_result)}[/dim]")
            console.print(f"[dim]Result: {create_result}[/dim]")
        return False

    def _create_segment(
        self,
        media_id: int,
        episode_number: int,
        segment: SegmentData,
        file_urls: dict[str, str] | None,
        max_retries: int = 3,
    ) -> bool:
        """Create a segment via API with retry logic for rate limiting."""
        if self.dry_run or not self.api_client:
            self._print(
                f"[cyan][DRY RUN] Would create segment: {segment.segment_hash} "
                f"({segment.content_ja[:30]}...)[/cyan]"
            )
            return True

        # Generate UUID from hash (or use existing)
        segment_uuid = str(uuid.uuid5(uuid.NAMESPACE_URL, segment.segment_hash))

        # Determine storage backend
        storage = (
            SegmentCreateRequestStorage.R2
            if self.storage_target == "r2"
            else SegmentCreateRequestStorage.LOCAL
        )

        request = SegmentCreateRequest(
            uuid=segment_uuid,
            position=segment.segment_index,
            start_time=self._ms_to_hmsff(segment.start_ms),
            end_time=self._ms_to_hmsff(segment.end_ms),
            content=segment.content_ja,
            content_spanish=segment.content_es if segment.content_es else UNSET,
            content_spanish_mt=segment.is_mt_es,
            content_english=segment.content_en if segment.content_en else UNSET,
            content_english_mt=segment.is_mt_en,
            actor_ja=segment.actor_ja if segment.actor_ja else UNSET,
            actor_es=segment.actor_es if segment.actor_es else UNSET,
            actor_en=segment.actor_en if segment.actor_en else UNSET,
            storage=storage,
            hashed_id=segment.segment_hash,
        )

        # Retry loop for rate limiting
        for attempt in range(max_retries):
            # Check global rate limit before making request
            _wait_for_rate_limit()

            # Acquire semaphore to limit concurrent requests
            with _request_semaphore:
                # Check rate limit again after acquiring semaphore
                _wait_for_rate_limit()

                # Wait for minimum delay between requests
                _wait_for_request_delay()

                result = self.segment_create.sync(
                    client=self.api_client, media_id=media_id, episode_number=episode_number, body=request
                )

            if result and not self._is_api_error(result):
                return True

            # Check if this is a duplicate key error (409) - segment already exists, treat as success
            if self._is_api_error(result) and self._get_error_attr(result, "status") == 409:
                # Segment already exists, skip silently
                return True

            # Check if this is a rate limit error that we can retry
            if self._is_api_error(result) and self._is_rate_limit_error(result):
                # Set global rate limit - all threads will wait for 60 seconds
                _set_rate_limit()
                self._print(
                    f"[yellow]Rate limited. All threads waiting {_RATE_LIMIT_WAIT_SECONDS}s...[/yellow]"
                )
                if attempt < max_retries - 1:
                    # Wait for rate limit to expire
                    _wait_for_rate_limit()
                    continue
                else:
                    self._print(f"[red]Max retries reached for segment {segment.segment_hash[:8]}[/red]")

            # Not a retryable error or max retries reached - print error details
            if self._is_api_error(result):
                self._print("\n[red]Failed to create segment:[/red]")
                self._print(f"  [red]Hash:[/red] {segment.segment_hash}")
                self._print(f"  [red]Position:[/red] {segment.segment_index}")
                self._print_api_error(result)
                self._print(f"  [red]Content:[/red] {segment.content_ja[:50]}...")
            else:
                self._print("[red]Failed to create segment: Unknown error[/red]")
                self._print(f"[dim]Result type: {type(result)}[/dim]")
                self._print(f"[dim]Result: {result}[/dim]")
            return False

        return False  # Shouldn't reach here, but just in case

    def upload_media(self, media_folder: Path, episode_filter: int | None = None) -> bool:
        """Upload a single media (all episodes and segments).

        Args:
            media_folder: Path to the media folder
            episode_filter: Optional episode number to filter upload
        """
        console.print(f"\n[bold cyan]Processing: {media_folder.name}[/bold cyan]")

        # Load media info
        media_info = self._load_media_info(media_folder)
        if not media_info:
            return False

        # Get or create media
        media_id = self._get_or_create_media(media_info, media_folder)
        if not media_id:
            return False

        # Skip episodes if update_info_only is True
        if self.update_info_only:
            console.print("[cyan]Info-only mode: Skipping episode/segment processing[/cyan]")
            return True

        # Process each episode folder
        episode_folders = sorted(
            [d for d in media_folder.iterdir() if d.is_dir() and not d.name.startswith("_")]
        )

        for episode_folder in episode_folders:
            try:
                episode_number = int(episode_folder.name)
            except ValueError:
                console.print(f"[yellow]Skipping non-episode folder: {episode_folder.name}[/yellow]")
                continue

            if episode_filter and episode_number != episode_filter:
                continue

            self.upload_episode(media_id, episode_folder)

        return True

    def _process_segment(
        self,
        media_id: int,
        episode_number: int,
        segment: SegmentData,
        episode_folder: Path,
        segment_index: int,
        total_segments: int,
    ) -> bool:
        """Process a single segment: upload files and create segment. Returns success status."""
        content_preview = segment.content_ja[:30] + "..." if len(segment.content_ja) > 30 else segment.content_ja

        # Check if segment should be skipped
        should_skip, skip_reason = self._should_skip_segment(segment)
        if should_skip:
            with self._stats_lock:
                if skip_reason == "no segment hash":
                    self.stats["skipped_no_hash"] += 1
                elif "no Spanish translation" in skip_reason or "no English translation" in skip_reason:
                    self.stats["skipped_no_translations"] += 1
                elif "content too long" in skip_reason:
                    self.stats["skipped_too_long"] += 1
                self.stats["total"] += 1
            self._print(f"  [{segment_index}/{total_segments}] {content_preview} - [dim]SKIPPED: {skip_reason}[/dim]")
            return True  # Return True so skipped segments don't count as failures

        file_urls: dict[str, str] = {}
        uploaded_files: list[str] = []
        skipped_files: list[str] = []

        # Upload files for this segment
        for file_type, filename in segment.files.items():
            if not filename:
                continue
            filepath = episode_folder / filename
            if not filepath.exists():
                continue

            if self.storage_target == "r2":
                r2_url = f"{self.config.r2_public_url}/media/{media_id}/{episode_number}/{filename}"
                if self.upload_r2:
                    if self.dry_run:
                        file_urls[file_type] = r2_url
                        uploaded_files.append(f"{filename} (dry-run)")
                    elif self.r2.file_exists(media_id, episode_number, filename):
                        file_urls[file_type] = r2_url
                        skipped_files.append(filename)
                    else:
                        url = self.r2.upload_file(filepath, media_id, episode_number)
                        if url:
                            file_urls[file_type] = url
                            uploaded_files.append(filename)
                        else:
                            uploaded_files.append(f"{filename} (FAILED)")
                else:
                    # Storage points at R2, but upload was not requested.
                    file_urls[file_type] = r2_url
            else:
                file_urls[file_type] = f"/assets/{media_id}/{episode_number}/{filename}"

        # Map file types for API
        mapped_urls = {}
        if file_urls:
            if "screenshot" in file_urls:
                mapped_urls["image_url"] = file_urls["screenshot"]
            if "audio" in file_urls:
                mapped_urls["audio_url"] = file_urls["audio"]

        # Create segment
        success = self._create_segment(media_id, episode_number, segment, mapped_urls or None)

        # Update statistics
        with self._stats_lock:
            self.stats["total"] += 1
            if success:
                self.stats["uploaded"] += 1
            else:
                self.stats["failed"] += 1

        # Log result
        status = "[green]OK[/green]" if success else "[red]FAILED[/red]"
        files_info = ""
        if uploaded_files:
            files_info += f" | uploaded: {', '.join(uploaded_files)}"
        if skipped_files:
            files_info += f" | skipped: {', '.join(skipped_files)}"

        self._print(f"  [{segment_index}/{total_segments}] {content_preview} - {status}{files_info}")

        return success

    def upload_episode(self, media_id: int, episode_folder: Path, max_workers: int = 8) -> bool:
        """Upload a single episode, processing segments in parallel."""
        console.print(f"\n[cyan]Processing episode: {episode_folder.name}[/cyan]")

        # Load episode data
        episode_data = self._load_episode_data(episode_folder)
        if not episode_data:
            return False

        # Get or create episode
        if not self._get_or_create_episode(media_id, episode_data):
            return False

        total = len(episode_data.segments)
        console.print(f"[green]Processing {total} segments (max {max_workers} parallel)...[/green]")

        success_count = 0

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(
                    self._process_segment,
                    media_id,
                    episode_data.number,
                    segment,
                    episode_folder,
                    i,
                    total,
                ): segment
                for i, segment in enumerate(episode_data.segments, 1)
            }

            for future in as_completed(futures):
                try:
                    if future.result():
                        success_count += 1
                except Exception as e:
                    segment = futures[future]
                    self._print(f"[red]  Segment {segment.segment_hash} - error: {e}[/red]")

        console.print(f"[green]Completed episode {episode_data.number}: {success_count}/{total} segments[/green]")

        # Print detailed statistics
        s = self.stats
        parts = []
        if s["skipped_no_hash"] > 0:
            parts.append(f"[dim]no hash: {s['skipped_no_hash']}[/dim]")
        if s["skipped_no_translations"] > 0:
            parts.append(f"[dim]no translations: {s['skipped_no_translations']}[/dim]")
        if s["skipped_too_long"] > 0:
            parts.append(f"[dim]too long: {s['skipped_too_long']}[/dim]")
        if s["failed"] > 0:
            parts.append(f"[red]failed: {s['failed']}[/red]")
        if parts:
            console.print(f"  Statistics: {', '.join(parts)}")

        return success_count == total


def scan_output_directory(output_path: Path) -> list[Path]:
    """Scan output directory for media folders."""
    media_folders = []

    for item in output_path.iterdir():
        if item.is_dir() and not item.name.startswith("_"):
            # Check if it has _info.json
            if (item / "_info.json").exists():
                media_folders.append(item)

    return sorted(media_folders, key=lambda x: x.name)


def _format_size(size_bytes: int) -> str:
    """Format bytes to human readable size."""
    for unit in ["B", "KB", "MB", "GB"]:
        if size_bytes < 1024.0:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.1f} TB"


def _collect_upload_info(
    media_folders: list[Path], episode_filter: int | None, r2_uploader: R2Uploader | None, upload_r2: bool = False
) -> dict:
    """Collect information about what will be uploaded."""
    total_media = len(media_folders)
    total_episodes = 0
    total_segments = 0
    total_files = 0
    total_size = 0

    media_details = []

    for media_folder in media_folders:
        # Load media info
        info_path = media_folder / "_info.json"
        if not info_path.exists():
            continue

        with open(info_path) as f:
            media_data = json.load(f)

        media_id = media_data.get("anilist_id", media_data.get("id"))
        media_title = media_data.get("romaji_name", media_folder.name)

        # Collect episodes
        episode_folders = sorted(
            [d for d in media_folder.iterdir() if d.is_dir() and not d.name.startswith("_")]
        )

        episodes_to_upload = []
        for episode_folder in episode_folders:
            try:
                episode_number = int(episode_folder.name)
            except ValueError:
                continue

            if episode_filter and episode_number != episode_filter:
                continue

            # Load episode data
            data_path = episode_folder / "_data.json"
            if not data_path.exists():
                continue

            with open(data_path) as f:
                episode_data = json.load(f)

            metadata = episode_data.get("metadata", {})
            segments = episode_data.get("segments", [])

            # Count files to upload (only if uploading to R2)
            episode_files = 0
            episode_size = 0
            if upload_r2:
                for segment in segments:
                    for file_type, filename in segment.get("files", {}).items():
                        if not filename:
                            continue
                        filepath = episode_folder / filename
                        if filepath.exists():
                            episode_files += 1
                            episode_size += filepath.stat().st_size

            episodes_to_upload.append(
                {
                    "number": episode_number,
                    "segments": len(segments),
                    "files": episode_files,
                    "size": episode_size,
                }
            )

            total_episodes += 1
            total_segments += len(segments)
            total_files += episode_files
            total_size += episode_size

        if episodes_to_upload:
            media_details.append(
                {
                    "id": media_id,
                    "title": media_title,
                    "episodes": episodes_to_upload,
                }
            )

    return {
        "total_media": total_media,
        "total_episodes": total_episodes,
        "total_segments": total_segments,
        "total_files": total_files,
        "total_size": total_size,
        "media_details": media_details,
    }


def _display_upload_summary(
    info: dict, target: str, storage_target: str, upload_r2: bool = False
) -> None:
    """Display a summary of what will be uploaded."""
    color = "red" if target == "prod" else ("cyan" if target == "dev" else "green")

    console.print(f"\n[bold {color}]{'='*60}[/bold {color}]")
    console.print(f"[bold {color}]UPLOAD SUMMARY[/bold {color}]")
    console.print(f"[bold {color}]{'='*60}[/bold {color}]")

    console.print(f"\n[bold]Media:[/bold] {info['total_media']}")
    console.print(f"[bold]Episodes:[/bold] {info['total_episodes']}")
    console.print(f"[bold]Segments:[/bold] {info['total_segments']}")
    console.print(f"[bold]API target:[/bold] {target}")
    console.print(f"[bold]Storage target:[/bold] {storage_target}")

    if storage_target == "r2" and upload_r2:
        console.print(f"[bold]Files to upload:[/bold] {info['total_files']}")
        console.print(f"[bold]Total size:[/bold] {_format_size(info['total_size'])}")
    elif storage_target == "r2":
        console.print("[dim]R2 upload: [bold]SKIPPED[/bold] (--upload-r2 not specified)[/dim]")
    else:
        console.print("[dim]Files to R2: [bold]N/A[/bold] (storage target is local)[/dim]")

    for media in info["media_details"]:
        console.print(f"\n[cyan]▸ {media['title']} (ID: {media['id']})[/cyan]")
        for ep in media["episodes"]:
            size_str = _format_size(ep["size"])
            console.print(
                f"  [dim]E{ep['number']:02d}[/dim] - {ep['segments']} segments, "
                f"{ep['files']} files, {size_str}"
            )

    console.print(f"\n[bold {color}]{'='*60}[/bold {color}]\n")


def upload_all(
    output_path: str,
    media_id: str | None = None,
    episode: int | None = None,
    env: str = "local",
    storage_target: str = "local",
    dry_run: bool = True,
    upload_r2: bool = False,
    update_info_only: bool = False,
) -> None:
    """Upload all media from the output directory.

    Args:
        output_path: Path to media folder (e.g., /path/to/output/12345)
        media_id: Ignored (kept for backwards compatibility). Use output_path directly.
        episode: Optional episode number to filter upload
        env: API environment to upload to (local, dev, or prod). Default is local.
        storage_target: Storage target for files ("local" or "r2").
        dry_run: Show what would be uploaded without actually uploading. Default is True.
        upload_r2: Actually upload files to R2. Only used when storage_target="r2".
        update_info_only: Only update media info (skip episodes and segments)
    """
    media_folder = Path(output_path).resolve()

    if not media_folder.exists():
        console.print(f"[red]Media folder does not exist: {media_folder}[/red]")
        return

    # Verify it's a valid media folder (has _info.json)
    if not (media_folder / "_info.json").exists():
        console.print(
            f"[red]Invalid media folder (missing _info.json): {media_folder}[/red]"
        )
        return

    if env not in ("local", "dev", "prod"):
        console.print(f"[red]Invalid environment: {env}. Must be 'local', 'dev', or 'prod'[/red]")
        return

    if storage_target not in ("local", "r2"):
        console.print(f"[red]Invalid storage target: {storage_target}. Must be 'local' or 'r2'[/red]")
        return

    if storage_target == "local" and upload_r2:
        console.print(
            "[red]Invalid combination: --upload-r2 requires --storage r2.[/red]"
        )
        return

    # Load config
    config = Config.from_env(env=env)
    if not config.validate(storage_target=storage_target, upload_r2=upload_r2):
        return

    # Display target
    config.display_target()

    # Check if episode filter exists
    if episode:
        episode_folder = media_folder / str(episode)
        if not episode_folder.exists() or not (episode_folder / "_data.json").exists():
            console.print(f"[yellow]No episode {episode} found in media folder[/yellow]")
            return

    # Collect and display upload info
    # Only initialize R2Uploader when we'll actually use it
    r2 = R2Uploader(config) if upload_r2 else None
    upload_info = _collect_upload_info([media_folder], episode, r2, upload_r2)

    if upload_info["total_files"] == 0 and not dry_run and storage_target == "r2" and upload_r2:
        console.print("[yellow]All files already uploaded. Nothing to do.[/yellow]")
        return

    _display_upload_summary(upload_info, config.target, storage_target, upload_r2)

    # Safety check for prod
    if config.is_prod and not dry_run:
        console.print(
            "[bold red] Type 'yes' to confirm upload to PRODUCTION: [/bold red]", end=""
        )
        if input() != "yes":
            console.print("[yellow]Upload cancelled.[/yellow]")
            return

    uploader = NadeshikoUploader(
        config,
        dry_run=dry_run,
        storage_target=storage_target,
        upload_r2=upload_r2,
        update_info_only=update_info_only,
    )

    # Upload the media
    if uploader.upload_media(media_folder, episode_filter=episode):
        console.print("\n[green]Upload complete![/green]")
    else:
        console.print("\n[red]Upload failed![/red]")
