"""Nadeshiko segment uploader.

Uploads media segments generated by media-sub-splitter to:
- Nadeshiko API (metadata)
- Cloudflare R2 (media files, optional - use --upload-r2 flag)

By default, only the backend is updated without uploading files to R2.
"""

import json
import os
import uuid
from dataclasses import dataclass
from datetime import timedelta
from pathlib import Path

import boto3
from botocore.exceptions import ClientError
from dotenv import load_dotenv
from rich.console import Console
from rich.progress import BarColumn, Progress, TaskID, TextColumn, TimeRemainingColumn

load_dotenv()

console = Console()

# R2 S3-compatible endpoint
R2_ENDPOINT_TEMPLATE = "https://{account_id}.r2.cloudflarestorage.com"


@dataclass
class Config:
    """Configuration from environment variables."""

    nadeshiko_api_key: str
    nadeshiko_base_url: str
    r2_account_id: str
    r2_access_key_id: str
    r2_secret_access_key: str
    r2_bucket: str
    r2_public_url: str
    is_prod: bool = False

    @classmethod
    def from_env(cls, env: str = "local") -> "Config":
        is_prod = env == "prod"

        if is_prod:
            # Prod requires separate env vars with explicit PROD suffix
            return cls(
                nadeshiko_api_key=os.getenv("NADESHIKO_PROD_API_KEY", ""),
                nadeshiko_base_url=os.getenv(
                    "NADESHIKO_PROD_BASE_URL", "https://api.nadeshiko.co"
                ),
                r2_account_id=os.getenv("R2_PROD_ACCOUNT_ID", ""),
                r2_access_key_id=os.getenv("R2_PROD_ACCESS_KEY_ID", ""),
                r2_secret_access_key=os.getenv("R2_PROD_SECRET_ACCESS_KEY", ""),
                r2_bucket=os.getenv("R2_PROD_BUCKET", "nadeshiko-segments"),
                r2_public_url=os.getenv("R2_PROD_PUBLIC_URL", ""),
                is_prod=True,
            )
        else:
            # Local is the default
            return cls(
                nadeshiko_api_key=os.getenv("NADESHIKO_API_KEY", ""),
                nadeshiko_base_url=os.getenv(
                    "NADESHIKO_BASE_URL", "http://localhost:5000"
                ),
                r2_account_id=os.getenv("R2_ACCOUNT_ID", ""),
                r2_access_key_id=os.getenv("R2_ACCESS_KEY_ID", ""),
                r2_secret_access_key=os.getenv("R2_SECRET_ACCESS_KEY", ""),
                r2_bucket=os.getenv("R2_BUCKET", "nadeshiko-segments"),
                r2_public_url=os.getenv("R2_PUBLIC_URL", ""),
                is_prod=False,
            )

    def validate(self) -> bool:
        """Check that required config is present."""
        prefix = "PROD_" if self.is_prod else ""

        missing = []
        if not self.nadeshiko_api_key:
            missing.append(f"NADESHIKO_{prefix}API_KEY")
        if not self.r2_account_id:
            missing.append(f"R2_{prefix}ACCOUNT_ID")
        if not self.r2_access_key_id:
            missing.append(f"R2_{prefix}ACCESS_KEY_ID")
        if not self.r2_secret_access_key:
            missing.append(f"R2_{prefix}SECRET_ACCESS_KEY")
        if not self.r2_bucket:
            missing.append(f"R2_{prefix}BUCKET")
        if missing:
            console.print(f"[red]Missing required env vars: {', '.join(missing)}[/red]")
            return False
        return True

    def display_target(self) -> None:
        """Display the upload target with appropriate styling."""
        if self.is_prod:
            console.print(
                "\n[bold red on white] TARGET: PRODUCTION [/bold red on white]\n"
                "[bold red] This will upload to PRODUCTION! [/bold red]"
            )
        else:
            console.print(
                "\n[bold green] TARGET: LOCAL [/bold green]\n"
                f"[dim] API: {self.nadeshiko_base_url}[/dim]"
            )


@dataclass
class SegmentData:
    """Segment data from _data.json."""

    segment_hash: str
    segment_index: int
    start_ms: int
    end_ms: int
    duration_ms: int
    content_ja: str
    content_es: str | None
    content_en: str | None
    is_mt_es: bool
    is_mt_en: bool
    actor_ja: str | None
    actor_es: str | None
    actor_en: str | None
    files: dict[str, str]  # audio, screenshot, preview, video filenames
    subtitles: dict  # ja, es, en subtitle details


@dataclass
class EpisodeData:
    """Episode data from _data.json."""

    number: int
    duration_ms: int
    total_segments: int
    segments: list[SegmentData]
    ignored_segments: list[dict]


@dataclass
class MediaInfo:
    """Media info from _info.json."""

    anilist_id: int
    japanese_name: str | None
    english_name: str | None
    romaji_name: str
    airing_format: str
    airing_status: str
    genres: list[str]
    version: str
    hash_salt: str


class R2Uploader:
    """Handles file uploads to Cloudflare R2."""

    def __init__(self, config: Config):
        self.config = config
        self.endpoint = R2_ENDPOINT_TEMPLATE.format(account_id=config.r2_account_id)
        self.bucket = config.r2_bucket
        self.public_url = config.r2_public_url

        self.s3_client = boto3.client(
            "s3",
            endpoint_url=self.endpoint,
            aws_access_key_id=config.r2_access_key_id,
            aws_secret_access_key=config.r2_secret_access_key,
        )

    def get_r2_key(self, media_id: int, episode_number: int, filename: str) -> str:
        """Generate R2 object key for a file."""
        return f"{media_id}/{episode_number}/{filename}"

    def upload_file(
        self, filepath: Path, media_id: int, episode_number: int, progress: Progress, task_id: TaskID
    ) -> str | None:
        """Upload a file to R2 and return its public URL."""
        key = self.get_r2_key(media_id, episode_number, filepath.name)

        try:
            self.s3_client.upload_file(
                str(filepath),
                self.bucket,
                key,
                Callback=lambda bytes_transferred: progress.update(
                    task_id, advance=bytes_transferred
                ),
            )
            # Return public URL
            return f"{self.public_url}/{key}"
        except ClientError as e:
            console.print(f"[red]Error uploading {filepath.name}: {e}[/red]")
            return None

    def file_exists(self, media_id: int, episode_number: int, filename: str) -> bool:
        """Check if a file already exists in R2."""
        key = self.get_r2_key(media_id, episode_number, filename)
        try:
            self.s3_client.head_object(Bucket=self.bucket, Key=key)
            return True
        except ClientError:
            return False


class NadeshikoUploader:
    """Handles uploading to Nadeshiko API and R2."""

    def __init__(self, config: Config, dry_run: bool = False, upload_r2: bool = False):
        self.config = config
        self.dry_run = dry_run
        self.upload_r2 = upload_r2
        self.r2 = R2Uploader(config)

        # Import SDK (optional - only if not dry run)
        if not dry_run:
            try:
                from nadeshiko import InternalNadeshiko

                self.client = InternalNadeshiko(
                    api_key=config.nadeshiko_api_key,
                    base_url=config.nadeshiko_base_url,
                )
            except ImportError:
                console.print(
                    "[yellow]Warning: nadeshiko SDK not found. "
                    "Install it with: uv pip install ../nadeshiko-sdk-python[/yellow]"
                )
                self.client = None
        else:
            self.client = None

    def _ms_to_hmsff(self, milliseconds: int) -> str:
        """Convert milliseconds to H:MM:SS.ffffff format."""
        td = timedelta(milliseconds=milliseconds)
        total_seconds = td.total_seconds()
        hours = int(total_seconds // 3600)
        minutes = int((total_seconds % 3600) // 60)
        seconds = total_seconds % 60
        return f"{hours}:{minutes:02d}:{seconds:06f}"

    def _load_media_info(self, media_folder: Path) -> MediaInfo | None:
        """Load _info.json from a media folder."""
        info_path = media_folder / "_info.json"
        if not info_path.exists():
            console.print(f"[yellow]No _info.json found in {media_folder}[/yellow]")
            return None

        with open(info_path) as f:
            data = json.load(f)

        return MediaInfo(
            anilist_id=data.get("anilist_id", data.get("id")),
            japanese_name=data.get("japanese_name"),
            english_name=data.get("english_name"),
            romaji_name=data.get("romaji_name"),
            airing_format=data.get("airing_format", "TV"),
            airing_status=data.get("airing_status", "FINISHED"),
            genres=data.get("genres", []),
            version=data.get("version", "1.0"),
            hash_salt=data.get("hash_salt", ""),
        )

    def _load_episode_data(self, episode_folder: Path) -> EpisodeData | None:
        """Load _data.json from an episode folder."""
        data_path = episode_folder / "_data.json"
        if not data_path.exists():
            console.print(f"[yellow]No _data.json found in {episode_folder}[/yellow]")
            return None

        with open(data_path) as f:
            data = json.load(f)

        metadata = data.get("metadata", {})
        segments = [
            SegmentData(
                segment_hash=s.get("segment_hash", ""),
                segment_index=s.get("segment_index", 0),
                start_ms=s.get("start_ms", 0),
                end_ms=s.get("end_ms", 0),
                duration_ms=s.get("duration_ms", 0),
                content_ja=s.get("content_ja", ""),
                content_es=s.get("content_es"),
                content_en=s.get("content_en"),
                is_mt_es=s.get("is_mt_es", False),
                is_mt_en=s.get("is_mt_en", False),
                actor_ja=s.get("actor_ja"),
                actor_es=s.get("actor_es"),
                actor_en=s.get("actor_en"),
                files=s.get("files", {}),
                subtitles=s.get("subtitles", {}),
            )
            for s in data.get("segments", [])
        ]

        return EpisodeData(
            number=metadata.get("number", 0),
            duration_ms=metadata.get("duration_ms", 0),
            total_segments=metadata.get("total_segments", 0),
            segments=segments,
            ignored_segments=data.get("ignored_segments", []),
        )

    def _get_or_create_media(self, media_info: MediaInfo) -> int | None:
        """Get existing media or create new one. Returns media ID."""
        if self.dry_run or not self.client:
            console.print(f"[cyan][DRY RUN] Would get/create media: {media_info.romaji_name}[/cyan]")
            return media_info.anilist_id

        # Try to find existing media by anilist_id
        result = self.client.media_index(params={"anilistId": str(media_info.anilist_id)})
        if result.is_ok and result.data and len(result.data) > 0:
            media_id = result.data[0].id
            console.print(f"[green]Found existing media: {media_id}[/green]")
            return media_id

        # Create new media
        create_result = self.client.media_create(
            body={
                "anilistId": media_info.anilist_id,
                "japaneseName": media_info.japanese_name or media_info.romaji_name,
                "romajiName": media_info.romaji_name,
                "englishName": media_info.english_name or media_info.romaji_name,
                "airingFormat": media_info.airing_format,
                "airingStatus": media_info.airing_status,
                "genres": media_info.genres,
                "category": "ANIME",
                "version": media_info.version,
                "hashSalt": media_info.hash_salt,
            }
        )

        if create_result.is_ok and create_result.data:
            media_id = create_result.data.id
            console.print(f"[green]Created new media: {media_id}[/green]")
            return media_id

        console.print(f"[red]Failed to create media: {create_result.error}[/red]")
        return None

    def _get_or_create_episode(self, media_id: int, episode_data: EpisodeData) -> bool:
        """Get existing episode or create new one."""
        if self.dry_run or not self.client:
            console.print(f"[cyan][DRY RUN] Would get/create episode: E{episode_data.number}[/cyan]")
            return True

        # Try to find existing episode
        result = self.client.episode_show(
            mediaId=str(media_id), episodeNumber=str(episode_data.number)
        )
        if result.is_ok and result.data:
            console.print(f"[green]Found existing episode: E{episode_data.number}[/green]")
            return True

        # Create new episode
        create_result = self.client.episode_create(
            body={"episodeNumber": episode_data.number},
            mediaId=str(media_id),
        )

        if create_result.is_ok:
            console.print(f"[green]Created new episode: E{episode_data.number}[/green]")
            return True

        console.print(f"[red]Failed to create episode: {create_result.error}[/red]")
        return False

    def _upload_segment_files(
        self,
        media_id: int,
        episode_number: int,
        segment: SegmentData,
        episode_folder: Path,
        progress: Progress,
        task_id: TaskID,
    ) -> dict[str, str] | None:
        """Upload all files for a segment and return URLs."""
        urls = {}
        files = segment.files

        for file_type, filename in files.items():
            if not filename:
                continue

            filepath = episode_folder / filename
            if not filepath.exists():
                console.print(f"[yellow]File not found: {filepath}[/yellow]")
                continue

            if self.upload_r2:
                # Check if already uploaded
                if self.r2.file_exists(media_id, episode_number, filename):
                    console.print(f"[dim]Already uploaded: {filename}[/dim]")
                    urls[file_type] = f"{self.r2.public_url}/{media_id}/{episode_number}/{filename}"
                    continue

                # Upload file
                url = self.r2.upload_file(filepath, media_id, episode_number, progress, task_id)
                if url:
                    urls[file_type] = url
            else:
                # Skip R2 upload - return public URL anyway for backend update
                urls[file_type] = f"{self.r2.public_url}/{media_id}/{episode_number}/{filename}"

        return urls if urls else None

    def _create_segment(
        self,
        media_id: int,
        episode_number: int,
        segment: SegmentData,
        file_urls: dict[str, str] | None,
    ) -> bool:
        """Create a segment via API."""
        if self.dry_run or not self.client:
            console.print(
                f"[cyan][DRY RUN] Would create segment: {segment.segment_hash} "
                f"({segment.content_ja[:30]}...)[/cyan]"
            )
            return True

        # Generate UUID from hash (or use existing)
        segment_uuid = str(uuid.uuid5(uuid.NAMESPACE_URL, segment.segment_hash))

        body = {
            "uuid": segment_uuid,
            "position": segment.segment_index,
            "startTime": self._ms_to_hmsff(segment.start_ms),
            "endTime": self._ms_to_hmsff(segment.end_ms),
            "content": segment.content_ja,
            "contentSpanish": segment.content_es,
            "contentSpanishMt": segment.is_mt_es,
            "contentEnglish": segment.content_en,
            "contentEnglishMt": segment.is_mt_en,
            "actorJa": segment.actor_ja,
            "actorEs": segment.actor_es,
            "actorEn": segment.actor_en,
        }

        # Add file URLs if uploaded
        if file_urls:
            if "screenshot" in file_urls:
                body["imageUrl"] = file_urls["screenshot"]
            if "audio" in file_urls:
                body["audioUrl"] = file_urls["audio"]

        result = self.client.segment_create(
            body=body, mediaId=str(media_id), episodeNumber=str(episode_number)
        )

        if result.is_ok:
            return True

        console.print(f"[red]Failed to create segment: {result.error}[/red]")
        return False

    def upload_media(self, media_folder: Path, episode_filter: int | None = None) -> bool:
        """Upload a single media (all episodes and segments).

        Args:
            media_folder: Path to the media folder
            episode_filter: Optional episode number to filter upload
        """
        console.print(f"\n[bold cyan]Processing: {media_folder.name}[/bold cyan]")

        # Load media info
        media_info = self._load_media_info(media_folder)
        if not media_info:
            return False

        # Get or create media
        media_id = self._get_or_create_media(media_info)
        if not media_id:
            return False

        # Process each episode folder
        episode_folders = sorted(
            [d for d in media_folder.iterdir() if d.is_dir() and not d.name.startswith("_")]
        )

        for episode_folder in episode_folders:
            try:
                episode_number = int(episode_folder.name)
            except ValueError:
                console.print(f"[yellow]Skipping non-episode folder: {episode_folder.name}[/yellow]")
                continue

            if episode_filter and episode_number != episode_filter:
                continue

            self.upload_episode(media_id, episode_folder)

        return True

    def upload_episode(self, media_id: int, episode_folder: Path) -> bool:
        """Upload a single episode (all segments)."""
        console.print(f"\n[cyan]Processing episode: {episode_folder.name}[/cyan]")

        # Load episode data
        episode_data = self._load_episode_data(episode_folder)
        if not episode_data:
            return False

        # Get or create episode
        if not self._get_or_create_episode(media_id, episode_data):
            return False

        # Upload segments
        console.print(f"[green]Uploading {len(episode_data.segments)} segments...[/green]")

        with Progress(
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
            TimeRemainingColumn(),
            console=console,
        ) as progress:
            # Calculate total file size for progress bar
            total_size = 0
            for segment in episode_data.segments:
                for file_type, filename in segment.files.items():
                    if filename:
                        filepath = episode_folder / filename
                        if filepath.exists():
                            total_size += filepath.stat().st_size

            task_id = progress.add_task(
                f"[cyan]Uploading E{episode_data.number}[/cyan]", total=total_size
            )

            for segment in episode_data.segments:
                # Upload files
                file_urls = self._upload_segment_files(
                    media_id, episode_data.number, segment, episode_folder, progress, task_id
                )

                # Map file types for API
                mapped_urls = {}
                if file_urls:
                    if "screenshot" in file_urls:
                        mapped_urls["image_url"] = file_urls["screenshot"]
                    if "audio" in file_urls:
                        mapped_urls["audio_url"] = file_urls["audio"]

                # Create segment
                self._create_segment(media_id, episode_data.number, segment, mapped_urls or None)

        console.print(f"[green]Completed episode {episode_data.number}[/green]")
        return True


def scan_output_directory(output_path: Path) -> list[Path]:
    """Scan output directory for media folders."""
    media_folders = []

    for item in output_path.iterdir():
        if item.is_dir() and not item.name.startswith("_"):
            # Check if it has _info.json
            if (item / "_info.json").exists():
                media_folders.append(item)

    return sorted(media_folders, key=lambda x: x.name)


def _format_size(size_bytes: int) -> str:
    """Format bytes to human readable size."""
    for unit in ["B", "KB", "MB", "GB"]:
        if size_bytes < 1024.0:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.1f} TB"


def _collect_upload_info(
    media_folders: list[Path], episode_filter: int | None, r2_uploader: R2Uploader, upload_r2: bool = False
) -> dict:
    """Collect information about what will be uploaded."""
    total_media = len(media_folders)
    total_episodes = 0
    total_segments = 0
    total_files = 0
    total_size = 0

    media_details = []

    for media_folder in media_folders:
        # Load media info
        info_path = media_folder / "_info.json"
        if not info_path.exists():
            continue

        with open(info_path) as f:
            media_data = json.load(f)

        media_id = media_data.get("anilist_id", media_data.get("id"))
        media_title = media_data.get("romaji_name", media_folder.name)

        # Collect episodes
        episode_folders = sorted(
            [d for d in media_folder.iterdir() if d.is_dir() and not d.name.startswith("_")]
        )

        episodes_to_upload = []
        for episode_folder in episode_folders:
            try:
                episode_number = int(episode_folder.name)
            except ValueError:
                continue

            if episode_filter and episode_number != episode_filter:
                continue

            # Load episode data
            data_path = episode_folder / "_data.json"
            if not data_path.exists():
                continue

            with open(data_path) as f:
                episode_data = json.load(f)

            metadata = episode_data.get("metadata", {})
            segments = episode_data.get("segments", [])

            # Count files to upload (only if uploading to R2)
            episode_files = 0
            episode_size = 0
            if upload_r2:
                for segment in segments:
                    for file_type, filename in segment.get("files", {}).items():
                        if not filename:
                            continue
                        filepath = episode_folder / filename
                        if filepath.exists():
                            # Check if already uploaded
                            if not r2_uploader.file_exists(media_id, episode_number, filename):
                                episode_files += 1
                                episode_size += filepath.stat().st_size

            episodes_to_upload.append(
                {
                    "number": episode_number,
                    "segments": len(segments),
                    "files": episode_files,
                    "size": episode_size,
                }
            )

            total_episodes += 1
            total_segments += len(segments)
            total_files += episode_files
            total_size += episode_size

        if episodes_to_upload:
            media_details.append(
                {
                    "id": media_id,
                    "title": media_title,
                    "episodes": episodes_to_upload,
                }
            )

    return {
        "total_media": total_media,
        "total_episodes": total_episodes,
        "total_segments": total_segments,
        "total_files": total_files,
        "total_size": total_size,
        "media_details": media_details,
    }


def _display_upload_summary(info: dict, is_prod: bool, upload_r2: bool = False) -> None:
    """Display a summary of what will be uploaded."""
    color = "red" if is_prod else "cyan"

    console.print(f"\n[bold {color}]{'='*60}[/bold {color}]")
    console.print(f"[bold {color}]UPLOAD SUMMARY[/bold {color}]")
    console.print(f"[bold {color}]{'='*60}[/bold {color}]")

    console.print(f"\n[bold]Media:[/bold] {info['total_media']}")
    console.print(f"[bold]Episodes:[/bold] {info['total_episodes']}")
    console.print(f"[bold]Segments:[/bold] {info['total_segments']}")

    if upload_r2:
        console.print(f"[bold]Files to upload:[/bold] {info['total_files']}")
        console.print(f"[bold]Total size:[/bold] {_format_size(info['total_size'])}")
    else:
        console.print(f"[dim]Files to R2: [bold]SKIPPED[/bold] (--upload-r2 not specified)[/dim]")

    for media in info["media_details"]:
        console.print(f"\n[cyan]▸ {media['title']} (ID: {media['id']})[/cyan]")
        for ep in media["episodes"]:
            size_str = _format_size(ep["size"])
            console.print(
                f"  [dim]E{ep['number']:02d}[/dim] - {ep['segments']} segments, "
                f"{ep['files']} files, {size_str}"
            )

    console.print(f"\n[bold {color}]{'='*60}[/bold {color}]\n")


def upload_all(
    output_path: str,
    media_id: str | None = None,
    episode: int | None = None,
    env: str = "local",
    dry_run: bool = False,
    upload_r2: bool = False,
) -> None:
    """Upload all media from the output directory.

    Args:
        output_path: Path to output directory containing processed media
        media_id: Optional media ID to filter upload
        episode: Optional episode number to filter upload
        env: Environment to upload to (local or prod). Default is local.
        dry_run: Show what would be uploaded without actually uploading
        upload_r2: Upload files to R2 (default is to only update the backend)
    """
    output_dir = Path(output_path).resolve()

    if not output_dir.exists():
        console.print(f"[red]Output path does not exist: {output_dir}[/red]")
        return

    if env not in ("local", "prod"):
        console.print(f"[red]Invalid environment: {env}. Must be 'local' or 'prod'[/red]")
        return

    # Load config
    config = Config.from_env(env=env)
    if not config.validate():
        return

    # Display target
    config.display_target()

    # Scan for media folders
    media_folders = scan_output_directory(output_dir)

    if not media_folders:
        console.print(f"[yellow]No media folders found in {output_dir}[/yellow]")
        return

    # Filter by media_id if specified
    if media_id:
        media_folders = [f for f in media_folders if f.name == media_id]
        if not media_folders:
            console.print(f"[yellow]No media folder found with ID: {media_id}[/yellow]")
            return

    # Check if episode filter exists
    if episode:
        episode_found = False
        for media_folder in media_folders:
            episode_folder = media_folder / str(episode)
            if episode_folder.exists() and (episode_folder / "_data.json").exists():
                episode_found = True
                break
        if not episode_found:
            console.print(f"[yellow]No episode {episode} found in selected media[/yellow]")
            return

    # Collect and display upload info
    r2 = R2Uploader(config)
    upload_info = _collect_upload_info(media_folders, episode, r2, upload_r2)

    if upload_info["total_files"] == 0 and not dry_run and upload_r2:
        console.print("[yellow]All files already uploaded. Nothing to do.[/yellow]")
        return

    _display_upload_summary(upload_info, config.is_prod, upload_r2)

    # Safety check for prod
    if config.is_prod and not dry_run:
        console.print(
            "[bold red] Type 'yes' to confirm upload to PRODUCTION: [/bold red]", end=""
        )
        if input() != "yes":
            console.print("[yellow]Upload cancelled.[/yellow]")
            return

    uploader = NadeshikoUploader(config, dry_run=dry_run, upload_r2=upload_r2)

    # Upload each media
    success_count = 0
    for media_folder in media_folders:
        if uploader.upload_media(media_folder, episode_filter=episode):
            success_count += 1

    console.print(
        f"\n[green]Upload complete: {success_count}/{len(media_folders)} media processed[/green]"
    )
